doc/CHANGES.rst
src/ZPublisher/BaseRequest.py
src/ZPublisher/tests/testBaseRequest.py

Prevent leaked connections when broken 'EndRequestEvent' subscribers raise

---

doc/CHANGES.rst
src/Zope2/Startup/warnfilter.py

backport of #22 to branch 2.13

Backport to 2.13: Queue additional warning filters at the beginning of the queue in order to allow overrides.

---

.gitignore
.travis.yml
doc/CHANGES.rst
doc/INSTALL-buildout.rst
doc/INSTALL-virtualenv.rst
doc/Makefile
doc/WHATSNEW.rst
doc/WSGI.rst
doc/_static/placeholder.txt
doc/_templates/placeholder.txt
doc/conf.py
doc/index.rst
doc/operation.rst

- Add docs for installation into a virtualenv.
- Update Sphinx paths to use `_` prefix.
Closes #30.

Document running under WSGI server.

---

doc/CHANGES.rst
src/ZPublisher/Iterators.py
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

I had troubles returning an IStreamIterator instance when using the WSGIPublisher.
This PR makes sure that no non iterator methods like seek, len and str are called when publishing an IStreamIterator.
Patch for master branch see: #28 
cheers

support IStreamIterator as WSGI response body

---

CHANGES.rst
src/App/FactoryDispatcher.py
src/Products/PageTemplates/ZopePageTemplate.py

These were discovered while trying to use the newest zope-packages for Plone (https://github.com/plone/Products.CMFPlone/issues/1351)
1. Cache-invalidation for FactoryDispatcher was broken for packages that are added after first initialization
2. No longer try to get removed help-file PageTemplate_Edit.stx

Fix two issues

---

doc/CHANGES.rst

Rendering of RestructuredText on PyPI https://pypi.python.org/pypi/Zope2/2.13.24 is broken. 
This little change fixes it. Looks much better now.
I also found a missing `-r` parameter in the example provided by the change log line and added it.
Hint: [zest.releaser](https://pypi.python.org/pypi/zest.releaser/) is the swiff knife for PyPI releases and besides a streamlined release process it offers the `longtest` script which introspects setup.py and renders README.rst, CHANGES.rst and other involved files as one long file. It reports errors and opens the result in the browser.

fix ReST rendering problem in changelog

---

src/OFS/dtml/access.dtml
src/OFS/role.py

Using hashed permission names instead of columns and rows numbers eliminates a security issue when the permission (or role) count changes. See #57 for more information.

Fixing permission handling

---

doc/CHANGES.rst
src/OFS/ObjectManager.py

It causes problems with ZCatalog indexes.
See https://github.com/zopefoundation/Zope/issues/69
This reverts pull request #62 from earlier this year.

Revert "Optimize 'OFS.ObjectManager.__contains__' method"

---

doc/CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

As described in the definition document by the ietf:
https://tools.ietf.org/html/draft-west-first-party-cookies-07
"The 'SameSite' attribute allows servers to assert that a cookie
ought not to be sent along with cross-site requests. This assertion
allows user agents to mitigate the risk of cross-origin information
leakage, and provides some protection against cross-site request
forgery attacks."

Add support for optional 'SameSite' cookie attribute

---

CHANGES.rst
src/Zope2/App/patches/__init__.py
src/Zope2/App/patches/persistence.py
src/Zope2/App/patches/publishing.py
src/Zope2/App/startup.py
src/Zope2/App/tests/test_startup.py

From Products.PloneHotfix20161129.
See https://github.com/zopefoundation/zope.interface/pull/65

Patch zope.interface to remove docstrings and avoid publishing.

---

src/Testing/ZopeTestCase/zopedoctest/functional.py

In functional doc tests you can apparently have a test case that has no runTest method.  Until now the Testing package added a dummy runTest method in that case, and set it to None.
But when this dummy runTest method gets called, you get an error:
Error in test runTest (Testing.ZopeTestCase.ZopeTestCase.FunctionalTestCase)
File ".../lib/python2.7/unittest/case.py", line 329, in run
testMethod()
TypeError: 'NoneType' object is not callable
Simply importing Testing.ZopeTestCase.FunctionalTestCase in a new test file may be enough to trigger this.
So this has something to do with the order in which tests are found.
I fixed it by making the dummy runTest method callable.
This is related to remarks in https://github.com/zopefoundation/Zope/pull/88, which is …

Fixed dummy runTest on functional test case. [2.13]

---

buildout.cfg
doc/CHANGES.rst
src/Zope2/App/tests/normal_zope3_page_template.pt
src/Zope2/App/tests/test_formatter.py
src/Zope2/App/tests/using_format_zope3_page_template.pt

Part of PloneHotfix20170117.
This pull request only adds tests, no other code.
This needs https://github.com/zopefoundation/AccessControl/pull/23 which has the real fix.
This was merged, but not released yet, so we add AccessControl to auto-checkout for now.

Test that `str.format` checks security for accessed attributes

---

requirements-full.txt
setup.py
src/Products/PageTemplates/expression.py
versions-prod.cfg

We do not need to convert the ast to source code before passing it to the
RestrictedPython machinery. It takes the result of the ast.parse() in Python 2.7 as well.
For Python 3 `slice()` has to be available as built-in so that has to be allowed as s in RestrictedPython.

Remove the dependency on sourcecodegen.

---

src/ZTUtils/Zope.py
src/ZTUtils/tests/testZope.py

https://github.com/zopefoundation/Zope/issues/15

Issue15 - Fix unicode handling in make_query()

---

CHANGES.rst
src/Testing/tests/test_testbrowser.py
src/ZPublisher/HTTPResponse.py

This should fix testbrowser related failures that suddenly saw Redirect exceptions being raised, rather than the redirects just being followed. This refs #106.

Restore `HTTPResponse.redirect` behaviour of not raising an exception.

---

CHANGES.rst
src/Testing/ZopeTestCase/zopedoctest/FunctionalDocTest.txt
src/ZPublisher/HTTPResponse.py
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

This is used as a hook by PluggableAuthService.
The HTTPResponse module has a new base class and two variants of the HTTP response class. You probably need to update the patch in PAS, to patch both `HTTPResponse.HTTPResponse` and `HTTPResponse.WSGIResponse`, as the `_unauthorized` method is defined on each of those classes.

Restore a `_unauthorized` hook on the response object.

---

CHANGES.rst
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

This should bring back the ability to register exception views for Unauthorized, without making any other changes. It does not address the issues raised in #106.

Restore exception views for unauthorized, closes #116.

---

.travis.yml
doc/CHANGES.rst
src/App/ApplicationManager.py

If you use [`experimental.publishtraverse`](https://pypi.python.org/pypi/experimental.publishtraverse) and try to call `manage_pack`, it warns that the object (the `manage_pack` function) has no roles. In strict mode it will fail.
This is an indication that the function *might* be available for anonymous users. That is not the case here, but being strict seems good.

Explicitly require Manager role for `AltDatabaseManager`.

---

src/App/ImageFile.py
src/OFS/CopySupport.py
src/OFS/DTMLMethod.py
src/OFS/Image.py
src/OFS/tests/testRanges.py
src/OFS/tests/test_DTMLMethod.py
src/Products/PageTemplates/ZopePageTemplate.py
src/Products/PageTemplates/tests/input/TeeShop1.html
src/Products/PageTemplates/tests/testZopePageTemplate.py
src/Products/PageTemplates/tests/test_engine.py
src/Testing/ZopeTestCase/ZopeLite.py
src/ZTUtils/Zope.py
src/Zope2/Startup/starter.py
src/Zope2/Startup/tests/test_starter.py

Special call out to `bytes(3)`, which produces `'3'` in Python 2 and `b'\x00\x00\x00'` in Python 3. I also like Python 3.5 and bringing back % formatting for bytes :(
This fixes another round of test failures. Logging in via basic auth is still broken, and request/response issues around headers and the body being str/bytes.
Python 3.4: 1118 tests, 45 failures, 36 errors and 1 skipped in 8.470 seconds.

More Python 3 fixes.

---

.travis.yml
buildout.cfg
tox.ini

@hannosch This is the solution I was actually hoping to find in Halle:  I added the `buildout:develop={toxinidir}` line which keeps all the buildouts in the tox environment directories.

Keep buildout artifacts in tox env dir.

---

buildout.cfg
requirements-full.txt
sources.cfg
versions-prod.cfg

This adds five.localsitemanager to the list of optional dependencies, which get tested with Zope2 and get a version pin.
I'd be open to adding more projects to the optional dependency list again, but don't have good criteria for what should and what shouldn't be tested by default. I'm thinking PAS might be another good candidate to include, as it is a wildly used low-level library. All of CMF is maybe a bit too big, but maybe all of CMFs dependencies might be a good idea.
My main goal is to make sure we don't break these additional libraries, when we make changes to Zope or update zope.* dependencies to new versions.

Start testing five.localsitemanager.

---

src/ZPublisher/Converters.py
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py
src/Zope2/App/startup.py

This deals with one test failure for processInputs.
The test failure for the file upload case changed from "it's not an iterator" to "operation on closed file".
I've been trying to figure out where that underlying BytesIO instance is closed, but couldn't figure it out so far. Commenting out the close call in `cgi.FieldStorage.__del__` seems to help, but I'm not sure why that is called early in the first place.

Py3 one more time

---

docs/maintenance.rst
setup.cfg

I'd like to start releasing wheels, at least for pure Python projects with universal code (Python 2 / 3 compatibility in one code base).
While buildout can only pick these up via an extension, I think it would be nice to start releasing them, so either those extension users or pip users can get their benefits.
Objections, thoughts?

Add universal wheel marker.

---

src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

This is a combination of three fixes. The tests had to be adjusted, as the cgi module in Python 3 won't work without a content-length header anymore. This is a side-effect of python/cpython@5c23b8e6ea7cdb0002842d16dbce4b4d716dd35a. Without the content length, the limit / read_bytes calculation is off, and we end up with three fieldstorage instances each with an empty byte, rather than one instance with a content of `test\n`.
The second part is a heavy handed workaround for closing the BytesIO instance underlying the FieldStorage too early. In Python 2.7, there wasn't a `__del__` defined yet. There's a good chance, a proper fix could also be related to http://bugs.python.org/issue23700 and http://bugs.python.org/issue18879, but I couldn't work out if something similar was indeed the issue …

Fix final Py3 test failure.

---

.travis.yml
update_index.sh

This is based on another project, where we (used to) re-build docs on Travis on a `gh-pages` branch after every tag (as well as pushes to`master`).

Auto-generate the release index on Travis when a tag is made.

---

CHANGES.rst
src/OFS/DTMLMethod.py
src/OFS/Image.py
src/Products/PageTemplates/ZopePageTemplate.py
src/Products/PageTemplates/www/ptEdit.zpt
src/Shared/DC/Scripts/BindingsUI.py
src/Shared/DC/Scripts/Script.py
src/Shared/DC/Scripts/dtml/scriptBindings.dtml
src/Shared/DC/Scripts/dtml/scriptTry.dtml

This pull request brings back the following tabs on the ZMI
* Image - View
* File - View
* DTML Method - View
* DTML Document - View
* PageTemplate - Test
* PageTemplate - Bindings
* PythonScript - Test
* PythonScript - Bindings
It basically reverts these commits @hannosch  did a while ago.
https://github.com/zopefoundation/Zope/commit/735105dab061aec1d2405c99155670ff2951a468
https://github.com/zopefoundation/Zope/commit/18ef29ca220c8f3e920eef58c0594ab09e03801f
Plus a few adjustments to make it working under python3.
As noted in issue #147, there should be a way to test/view these objects via the ZMI.
I'm not quite sure why these tabs have been removed in the first place.
I don't see a big problem with the code itself and they also very useful in the way I
use the Zope.
However I'm pretty …

Bring back some tabs on the ZMI

---

CHANGES.rst
src/Testing/ZopeTestCase/zopedoctest/FunctionalDocTest.txt
src/Testing/ZopeTestCase/zopedoctest/functional.py

[Some tests](https://github.com/zopefoundation/five.formlib/blob/master/src/five/formlib/tests/forms.txt) in `five.formlib` pass a multipart message to the http helper function. When using the default parser in the `email` module, the payload of multipart messages are a list of messages instead of a string for non_multipart messages.   
This PR fixes that and ensures that the encoding is not failing with utf-8 encoded in the request body.

Fix handling of multipart requests in functional doctests.

---

src/Testing/ZopeTestCase/sandbox.py
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_pubevents.py

Hi,
this could be a fix for #103 to explicitly open/close the connection to ZODB/Zeo.
In theory the `__getattr__` and `__bobo_traverse__` methods could be removed from
the `ZApplicationWrapper`, because `WSGIPublisher` does not use them any more.
However there is the (deprecated ?) ZServer, which still relies on them. So I did not dare to remove these two methods.
The more tricky bit was to adjust the unittests to work with the changed behaviour of the publisher. I found no way around the monkey patch in `sandboxy.py`

Use a context manager to explicitly open/close the ZODB connection.

---

src/OFS/Application.py
src/OFS/ObjectManager.py
src/ZPublisher/BaseRequest.py

This removes two exceptions and one import-lock from the normal traversal logic used in the WSGI publisher.
I did some unscientific benchmarks using `ab` with a database with just one page template called `index_html` with the default page template example content. Requests where done against ``http://127.0.0.1:8080/`` using a couple different concurrency settings.
Under Python 2.7 performance went up from ~500 requests/sec to ~800 requests/sec. Under Python 3.5 it went up from ~300 request/sec to ~700 requests/sec. Under Python 3.6 it went up from ~500 requests/sec to ~1000 requests/sec. That matches the general assumption that Python 3.6 is the first release with overall on-par or sometimes better performance compared to Python 2.7.
I think the main source here is avoiding the import …

Small speed-ups, avoid raising two exceptions during traversal.

---

src/ZPublisher/WSGIPublisher.py

Before the rework to use a context manager the transaction was aborted directly
on the transaction manager. We still need to do this as an Unauthorized would
not be raised but lead to a `Cannot close a connection joined to a
transaction`.
This fixes a regression introduced by #155.

Abort the transaction before closing the connection.

---

CHANGES.rst
src/App/ApplicationManager.py

This fixes #159.  A startup with an old ZODB from Zope 2.13 is now possible.

Make ApplicationManger persistent again.

---

src/App/ZApplication.py
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

This can happen if exceptions happen inside exception views or publication event handlers (e.g. PubFailure).
Refs #103, #168.

Avoid additional transaction abort, if the transaction is already closed

---

CHANGES.rst
requirements-full.txt
setup.py
src/Zope2/Startup/handlers.py
src/Zope2/Startup/starter.py
src/Zope2/Startup/tests/test_handlers.py
versions-prod.cfg

This uses the ipaddress library (part of the stdlib in Python 3) instead of a regular expression.
The alternative would have been to use the regex from ZConfig (https://github.com/zopefoundation/ZConfig/blob/master/ZConfig/datatypes.py#L285), but that looked incomprehensible to me ;)

Add support for IPv6 addresses for the trusted-proxy zope.conf setting.

---

src/OFS/Application.py
src/OFS/tests/testAppInitializer.py

This should fix #187.
It only broke for Products, whose `__init__` module contained a non-empty `misc_` variable. I'm not sure anymore what was once stored in that module global variable, but none of the core Products contain one anymore.
`Application.misc_` is a class (and not an instance), so assigning to the class dict fails now. Only the `setattr` change of this commit is strictly required, the test works either way (the dict/mappingproxy support `__contains__`).

Fix install_product for products with a non-empty `misc_` attribute.

---

buildout.cfg

This only applies to Python 2.7, but it doesn't hurt to specify it for Python 3 (where it is enabled by default).
Testing with randomized hashes ensures we don't introduce hash ordering dependent code into Python 2.7 only code paths.

Set the Python hash seed to random during tests.

---

CHANGES.rst
src/Testing/tests/test_testbrowser.py
src/ZPublisher/httpexceptions.py

When using a programmatically defined WSGI pipeline which contains `HTTPExceptionHandler` as one of its steps setting `browser.handleErrors = False` was ignored.

Fix HTTPExceptionHandler to be usable in WSGI pipeline of testbrowser tests.

---

doc/INSTALL-virtualenv.rst

Using the previously described variant using the index led to a broken installation because `pip` installs `Products.ZCatalog` 4.x. It expects to find `products.zcatalog` in the index. (Even downgrading to pip 1.5 does not help.)

Use the requirements as the index is broken

---

CHANGES.rst
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py
src/ZPublisher/tests/test_pubevents.py

Raise the publish exception immediately rather than trying to return an exception response if the client requested this by setting the `wsgi.handleErrors` environ key to False. This is set by zope.testbrowser when the browser's `handleErrors` attribute is set to False. This restores behavior from Zope 2 that a number of Plone tests depend on in order to be able to inspect the actual exception raised by the app rather than a rendered response.

Raise app exceptions without rendering response if wsgi.handleErrors is False

---

src/App/Common.py
src/OFS/CopySupport.py
src/OFS/FindSupport.py
src/OFS/Moniker.py
src/OFS/ObjectManager.py
src/OFS/SimpleItem.py
src/Products/PageTemplates/Expressions.py
src/Products/PageTemplates/expression.py
src/Testing/ZopeTestCase/placeless.py
src/ZPublisher/HTTPRequest.py

Go back to using the `callable` builtin to see if an object is callable. We saw problems with some views that were instances of collections.Callable but did not actually have a `__call__` method. And while `callable` was removed for Python 3.0-3.1, it has returned.

revert to callable() check

---

CHANGES.rst
src/Products/Five/browser/metaconfigure.py
src/Products/PageTemplates/Expressions.py
src/Products/PageTemplates/tests/testExpressions.py

This fixes a regression from Zope 2: if a browser view does not implement `__call__`, traversing to it in a path expression should return the view instance itself rather than raising an AttributeError. `callable()` was returning a false positive in this case, probably tricked by the `__call__` property on the view superclass.
(Zope 2 caught the AttributeError and checked to see if its parameter was `__call__`, but I figure catching NotImplementedError matches the intent better.)

Fix path expressions with uncallable views

---

src/Testing/ZopeTestCase/functional.py
src/Testing/ZopeTestCase/zopedoctest/functional.py
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

Also fix `zopedoctest.functional.http` to support binary bodies.

Follow-up to #199, don't use `wsgi.handleErrors`.

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py

it is shared by HTTPResponse and WSGIResponse.
Found in `./bin/test -s Products.CMFPlone -t test_PloneTool_deleteObjectsByPaths`
```
[0]   /Users/pbauer/workspace/coredev/parts/test/bin/test(441)<module>()
[1]   /Users/pbauer/.cache/buildout/eggs/collective.xmltestreport-1.3.4-py2.7.egg/collective/xmltestreport/runner.py(60)run()
-> failed = run_internal(defaults, args, script_parts=script_parts)
[2]   /Users/pbauer/.cache/buildout/eggs/collective.xmltestreport-1.3.4-py2.7.egg/collective/xmltestreport/runner.py(73)run_internal()
-> runner.run()
[3]   /Users/pbauer/.cache/buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py(160)run()
-> self.run_tests()
[4]   /Users/pbauer/.cache/buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py(242)run_tests()
-> …
```

Move _html to HTTPBaseResponse 

---

CHANGES.rst
src/Shared/DC/Scripts/Bindings.py
src/Shared/DC/Scripts/Signature.py
src/ZPublisher/BeforeTraverse.py

If the instance was created before Zope 4.0b2 unpickling broke because in 4.0b2 all classes became new-style classes.
Fixes #205.
The proposes solution seems to work as shown in #205.
Could anyone think of a cleaner solution?

Fix unpickling of instances those base class changed to a new-style class.

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py

When publishing image (bytes) responses without content-type a UnicodeDecodeError is raised.
Found when debuggung the failing test in Plone `testPublishFTPScaleViaUID`. 
Here is a session with a pdb just before `if self.isHTML(body.decode(self.charset)):`
```
$ ./bin/test -t testPublishFTPScaleViaUID
Running plone.app.imaging.testing.ImagingTestCase:Functional tests:
Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
Set up plone.testing.z2.Startup in 0.114 seconds.
Set up plone.app.testing.layers.PloneFixture in 8.322 seconds.
Set up plone.app.imaging.testing.ImagingFixture in 2.049 seconds.
Set up plone.app.imaging.testing.ImagingTestCase:Functional in 0.000 seconds.
Running:
1/1 (100.0%) testPublishFTPScaleViaUID (plone.app.imaging.tests.test_new_scaling.ImagePublisherTests)[14] > …
```

Prevent UnicodeDecodeError

---

src/ZPublisher/HTTPResponse.py

Same as the unmerged commit https://github.com/zopefoundation/Zope/pull/174/commits/727612db36456ea389a7b612acc1046bb975664b by @mauritsvanrees from https://github.com/zopefoundation/Zope/pull/174

Avoid error when calling setBody with lock on a wsgi response.

---

src/Products/Five/browser/configure.zcml

Fixes #211
This is more of a blind stab at the problem. I couldn't find any other plausible references, so I tentatively removed this line (which doesn't make a lot of sense to me anyway). The warning is now gone. I've seen no obvious problems.
But I am completely ignorant as to potential side effects, so I'm posting this in the hope that someone more knowlegeable will confirm this is OK.

Removed reference to old action.html

---

CHANGES.rst
src/Testing/ZopeTestCase/functional.py
src/Testing/ZopeTestCase/zopedoctest/functional.py

The request makes a sanitized copy of its environ, so the functional test wrappers need to set x-wsgiorg.throw_errors earlier. Also this was missing from zopedoctest/functional.py

Set x-wsgiorg.throw_errors earlier because request copies its environ

---

doc/CHANGES.rst
src/ZServer/tests/test_config.py

See the failures in https://github.com/zopefoundation/Zope/pull/226.
On the master branch we already did basically the same in [February 2016](https://github.com/zopefoundation/Zope/pull/47)
For 2.13 we still support Python 2.6, so I did not use `unittest.skipIf`.

Skip IPv6 tests on Travis, as it is not supported.

---

CHANGES.rst
src/Zope2/App/tests/test_safe_formatter.py
src/Zope2/App/tests/using_format_zope3_page_template.pt

The real fix is in the AccessControl package, already released in 4.0b1.
Part of PloneHotfix20171128.
Same as PR #232, but now for master.

Test that `str.format` checks security for accessed keys and items. [master]

---

CHANGES.rst
src/OFS/dtml/renameForm.dtml

`Image` and `File` do not have an `id` (no more).
Fixes #247.

Fix renaming of images and files via ZMI.

---

CHANGES.rst
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

If `publish_module` is called with a `_response` parameter which is not `None` its stdout is written to but is not read from.
Detected in zopefoundation/Products.ExternalEditor#10.

Use correct stdout stream in publish_module.

---

src/Testing/ZopeTestCase/functional.py
src/Testing/ZopeTestCase/zopedoctest/FunctionalDocTest.txt
src/Testing/ZopeTestCase/zopedoctest/functional.py

I took this commit from the `plonezope4` branch aka #174.
Is it still relevant?

fix regression in doctest functional helper: sort headers

---

buildout.cfg
doc/CHANGES.rst
src/OFS/CopySupport.py
src/OFS/tests/testCopySupport.py

6ca3691 introduces code to prevent a DoS attack.
This is PR mitigates the consequences for file system code by allowing to paste without limits as discussed in #217 for Zope 2.13.

Add ability to paste objects without limits. [2.13]

---

CHANGES.rst
src/OFS/Image.py
src/OFS/tests/testFileAndImage.py

In both Python 2 and 3, the tag() method returns the respective str type, so
the result can always be used for `__str__`. Without having this method
available in Python 3, the image tag cannot be included, for example, in
Chamaeleon page templates by simply accessing the image object, as that uses
i18n which in turn casts the object to the respective text (unicode) type. Not
implementing `__str__` in Python 3 results in the object representation instead
of the tag in that case.

make FSImage.__str__ available in Python 3

---

CHANGES.rst
src/OFS/DTMLDocument.py
src/OFS/DTMLMethod.py
src/OFS/tests/test_DTMLDocument.py
src/OFS/tests/test_DTMLMethod.py

Without this change uploading a file to a DTMLMethod via ZMI breaks because `self.munge(file)` tries to use a string regex on a bytes object (the `file` variable). 
What do you think is this patch the way to go?
Open tasks:
See zopefoundation/Products.SiteErrorLog#11 which uses this method in tests and fails with `AttributeError: 'str' object has no attribute 'read'`. in OFS/DTMLMethod.py:272

Fix DTML upload for Python 3.

---

buildout.cfg

Before this change the scripts of the Zope package where created three times.
The last created version was the one by `allpy`. That means that `bin/runwsgi`
contained all test eggs.
Now each script is only created once with its own scope. I think this makes it
clearer what each script contains.

Create all scripts only once.

---

docs/zope2book/SearchingZCatalog.rst

The sentence "On the other hand, cataloging a complex object when it changes" ends abrupt and is missing the message.
Imho cataloging a complex object could be too time consuming - which is exactly what I added to the text.
Also, I wrapped the paragraphs at 80 characters, which is was Tres told me a while ago, see
https://github.com/zopefoundation/Zope/pull/261#pullrequestreview-106874625

complete abrupt ending sentence

---

docs/zope2book/SearchingZCatalog.rst

fix spelling error

---

CHANGES.rst
src/ZPublisher/BaseRequest.py
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py
src/ZPublisher/tests/test_xmlrpc.py
src/ZPublisher/xmlrpc.py
tox.ini

This restores support for XML-RPC when running in Python 3 with the WSGI publisher instead of ZServer. It turns out that we need this to run Plone's browser-based functional tests, because robotframework uses XML-RPC to get the available test keywords.
Mostly this involves moving the `xmlrpc` module back from ZServer.ZPublisher to ZPublisher, along with the corresponding tests. The XML-RPC implementation doesn't depend on using the ZServer, so I think it still belongs in Zope itself.
I fixed a couple Python 3 compatibility issues in `xmlrpc.py`:
- Import from xmlrpc.client instead of xmlrpclib
- Make sure that our override of the code for dumping an arbitrary object instance takes effect in both Python 2 and 3
I also had to work around a Python bug (https://bugs.python.org/issue27777) …

Re-add support for XML-RPC

---

src/zmi/styles/resources/zmi_base.js

Otherwise, the `ajaxComplete` callback might be added multiple times in case the modal in aborted without submission.
Fixes #327 .

Do all DOM modifications directly on the complete callback.

---

CHANGES.rst
src/Products/PageTemplates/PageTemplateFile.py
src/Products/PageTemplates/tests/testZopePageTemplate.py
src/Products/PageTemplates/tests/test_ptfile.py
src/Products/PageTemplates/tests/utf8.xml
src/Products/PageTemplates/utils.py

Fix XML Page template files in Python 3

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/WSGIPublisher.py

as proposed in https://github.com/plone/plone.rest/pull/75#issuecomment-404971502.

create exception view before handling Unauthorized

---

src/OFS/ObjectManager.py
src/OFS/tests/testSorting.py
src/OFS/zpt/main.zpt

Instead of obtaining the list of objects from `objectValues` and assuming that these provide all necessary attributes (like `getId()`), a list of dictionaries is created on the basis of `objectItems`, which has access to the object's ID as it is known to the parent. This is used for sorting as well as interaction with the specific items, so it allows to show broken objects and also delete them.
fixes #311 
fixes #213

Fix handling of broken objects in ZMI

---

.gitignore
README.rst
constraints.txt
docs/INSTALL-pipenv.txt
docs/INSTALL-virtualenv.rst
requirements-full.txt
util.py

This needs a change which requires an additional step if you install via pip and want to use ZServer. We did explicitly not document installation via pipenv with python 2.
This fixes #272.

Support for installing zope via pipenv #272

---

docs/zdgbook/Acquisition.rst
docs/zdgbook/AppendixA.rst
docs/zdgbook/ComponentsAndInterfaces.rst
docs/zdgbook/GettingStarted.rst
docs/zdgbook/Introduction.rst
docs/zdgbook/ObjectPublishing.rst
docs/zdgbook/Products.rst
docs/zdgbook/Security.rst
docs/zdgbook/TestingAndDebugging.rst
docs/zdgbook/ZODBPersistentComponents.rst
docs/zdgbook/includes/zope2_notice.rst

This is the first step for #252.
Hereafter the documents will be updated to work with Zope 4/Python 3 one by one.

Add notice that dev guide was written for Zope 2

---

CHANGES.rst
src/Zope2/Startup/datatypes.py
src/Zope2/Startup/tests/test_schema.py

Prevent breaking page rendering when setting `default-zpublisher-encoding` in `zope.conf` on Python 2.
Fixes #308.

Fix #308: default-zpublisher-encoding breaks rendering

---

CHANGES.rst
src/Products/Five/component/browser.py

This fixes an issue that was causing some Plone tests to end up with the wrong base site manager.

Fix test layer isolation issue

---

src/Products/SiteAccess/VirtualHostMonster.py
src/Products/SiteAccess/tests/testVirtualHostMonster.py

from https://bugs.launchpad.net/zope2/+bug/699865 :
VirtualHostMonster does not work with IPv6 named hosts.
In case of such rewrite configuration:
RewriteRule (.*) http://10.0.243.129:9280/VirtualHostBase/https/[%{SERVER_ADDR}]:4080$1 [L,P]
When SERVER_ADDR is fd00::74ba VirtualHostMonster dies with:
File "/eggs/Zope2-2.12.14-py2.6-linux-x86_64.egg/ZPublisher/BeforeTraverse.py", line 145, in __call__
meth(*(container, request, None)[:args])
File "/eggs/Zope2-2.12.14-py2.6-linux-x86_64.egg/Products/SiteAccess/VirtualHostMonster.py", line 154, in __call__
host, port = host.split(':')
ValueError: too many values to unpack
This is because IPv6 addresses contain ":" in them.

SiteAccess: Make VirtualHostMonster support IPv6

---

CHANGES.rst
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

On Python 2 everything is fine only on Python 3 the recoding has to be done.
This regression was introduced in #181.

Fix handling of non-ASCII characters in URLs.

---

doc/CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py
version_ranges.cfg

Port the fix for #375 to Zope 2.13.

Zope 2.13: password possibly revealed in HTTPRequest.text() method

---

src/Products/SiteAccess/VirtualHostMonster.py
src/Products/SiteAccess/tests/testVirtualHostMonster.py

from https://bugs.launchpad.net/zope2/+bug/699865 :
VirtualHostMonster does not work with IPv6 named hosts.
In case of such rewrite configuration:
RewriteRule (.*) http://10.0.243.129:9280/VirtualHostBase/https/[%{SERVER_ADDR}]:4080$1 [L,P]
When SERVER_ADDR is fd00::74ba VirtualHostMonster dies with:
File "/eggs/Zope2-2.12.14-py2.6-linux-x86_64.egg/ZPublisher/BeforeTraverse.py", line 145, in __call__
meth(*(container, request, None)[:args])
File "/eggs/Zope2-2.12.14-py2.6-linux-x86_64.egg/Products/SiteAccess/VirtualHostMonster.py", line 154, in __call__
host, port = host.split(':')
ValueError: too many values to unpack
This is because IPv6 addresses contain ":" in them.
--
This is backport of https://github.com/zopefoundation/Zope/pull/314 to
2.13 branch …

Zope 2.13: SiteAccess: Make VirtualHostMonster support IPv6

---

CHANGES.rst
src/OFS/DTMLMethod.py
src/OFS/Image.py
src/OFS/SimpleItem.py
src/Products/PageTemplates/ZopePageTemplate.py

This no longer requires child classes to do so.
See zopefoundation/Products.CMFCore#53.

Add security declarations to SimpleItem's FTP methods.

---

doc/CHANGES.rst
src/OFS/Image.py
src/OFS/tests/testFileAndImage.py

Use the standard history page, enabled using the same condition than the one
that enables the text area on edit (ie. the file must be text or javascript and
reasonably sized)

Enable history page for OFS.Image.File

---

src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie , the date used on expires should be in the same format as Date on HTTP Header.
As of Firefox 60.3.0esr, passing the date in any other format doesn't work and is ignored by the browser.

Update expire date on expireCookie function

---

appveyor.yml

https://www.appveyor.com/docs/windows-images-software/#python does not
list Python 3.8 as an available version.
(In fact Python 3.8 is not out yet.)
Having it listed in appveyor.yml confuses tools like my
check-python-versions, as they detect an inconsistency between supported
Python versions listed in appveyor.yml with those listed eg. in
setup.py.

There's no Python 3.8 on Appveyor

---

CHANGES.rst
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

See #413, item [3].
Because we do not have a special handling for `ConflictError` in the exception view code, the exception view for `IException` has to be unregistered as it otherwise prevents the `ConflictError` to propagate to the except block which does the retry handling.

Retry: fix closing newly created request before processing

---

docs/zdgbook/ObjectPublishing.rst

This pull request includes:
- delete double leading whitespaces between sentences
- delete trailing whitespaces
- delete trailing double newline
My original plan #440 was to revise the chapter "Object Publishing" within one pull request.
This document has not been touched much in the last decade - there are whitespace issues, typos, hard to understand sentences and of course out of date information, concerning the upcoming Zope 4 / wsgi setup.
Doing all the changes in one pull request would mean changing almost all of the 1300 lines of documentation for multiple reasons. Nobody would like to review these massive changes.
That's why I plan to do one pull request at a time, fixing one issue - or one subchapter /section.
Though, the documentation has not received much love lately, I really …

Fix whitespace issues - first pull request in a series to completely revise chapter "Object Publishing"

---

.travis.yml

cf. https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
and https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Remove "sudo" tag as it is deprecated.

---

docs/INSTALL-pip.rst
docs/index.rst

It was called "Install into a virtualenv" but actually a better name is "Install via pip", as also the other ways of installation  (via buildout and via pipenv)  make use of a virtualenv.

Update name of installation document

---

CHANGES.rst
src/OFS/Folder.py

The View tab on OFS.Folder and derivatives was very useful and should be restored.
fixes #449

Restore the `View` ZMI tab on folders and their subclasses

---

CHANGES.rst
docs/zope2book/AdvZPT.rst
src/Zope2/utilities/skel/etc/wsgi.conf.in

- Document filesystem caching for Chameleon page templates

---

CHANGES.rst
src/Testing/ZopeTestCase/zopedoctest/functional.py
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

I'm testing the waters here. This should probably not get merged before some reasonable time to object has passed so people have time to speak up.
As the headers disclose unnecessary information and my search engine fu on what would still rely on them leads to only the implementation and a discussion from 2003 on whether to drop them or not, I'm thus betting BCI to be dead and unused at this point.
I'm also open to making this configurable, if this is still actually used for something.

Remove support for Bobo Call Interface headers

---

CHANGES.rst
docs/zdgbook/ObjectPublishing.rst
docs/zdgbook/TestingAndDebugging.rst
docs/zope2book/MaintainingZope.rst
src/Zope2/Startup/handlers.py

This environment variable is no longer valid. Still, it has been
referenced, both in code by a setter, and several times in the
documentation.
The focus of this commit was to remove the references, not to fix
the documenation about how to debug Zope, as the whole documenation
will be amended, anyway - step by step.
modified:   docs/zdgbook/TestingAndDebugging.rst
modified:   docs/zope2book/MaintainingZope.rst
modified:   src/Zope2/Startup/handlers.py

Remove obsolete environment var

---

docs/zdgbook/ObjectPublishing.rst
docs/zdgbook/TestingAndDebugging.rst

... from documenation, as it had been removed already 2003.
cf https://github.com/zopefoundation/Zope/commit/688d79acc94624b1f477879cf531bd28f806e873
Also, the section about getting debug and profiling information from Control Panel was removed.
No skipped ci, as otherwise only admins could merge.

Remove reference to env variable PROFILE_PUBLISHER

---

src/ZPublisher/WSGIPublisher.py

ConflictError is no longer referenced, so the import should also go away.

remove import of ConflictError

---

CHANGES.rst
src/OFS/ObjectManager.py
src/OFS/tests/testObjectManager.py
src/OFS/zpt/main.zpt

Fixes #391 
The ZMI list view simply used the object's ID to construct the relative link for visiting the object. This works whenever the ID doesn't start with a character that has special meaning in URLs, like `#`. 
The fix adds another element to the mapping being iterated over which contains a URL-quoted representation of the ID, which is now used to construct that link.

Fix faulty ZMI links due to missing URL-quoting

---

.travis.yml
doc/CHANGES.rst
setup.py
tox.ini

Zope 2.13: Drop Python 2.6 support.

---

docs/zdgbook/ObjectPublishing.rst

... in section "URL Traversal" in chapter ObjectPublishing of the Zope Developer's Guide.
Slowly but surely.
[ci-skip]

Fix minor wording and formatting issues

---

docs/zdgbook/ObjectPublishing.rst
src/Zope2/Startup/handlers.py

The Z_REALM environment variable is no longer used to control the
realm name of a basic auth dialog.

Remove references to obsolete Z_REALM

---

docs/zdgbook/ObjectPublishing.rst

- interfaces are neither listed nor mentioned where to find
- hard to understand
- more detailed infos are provided later in section "4.10.7. Publishable Module"

Remove section "Traversal Interfaces"

---

src/ZPublisher/WSGIPublisher.py

Only mark the events when the request will actually be retried.
Fixes a issue uncovered in https://github.com/plone/buildout.coredev/pull/564

Don't always flag PubBeforeAbort and PubBeforeAbort as retry

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/test_WSGIPublisher.py

Fixes #216 
Expands #215 
I'm in favor of following the `HTTPResponse` behavior because IMHO there is no good reason for just discarding the lock semantics.

Make sure the WSGI Response object respects lock semantics

---

CHANGES.rst
src/Products/PageTemplates/engine.py
src/Products/PageTemplates/tests/macros.pt
src/Products/PageTemplates/tests/test_engine.py

Fixes #210 
Under Zope 2.13, the `macros` attribute on a page template is a dictionary. The security machinery didn't care about it. With Chameleon, it is a real object.
`__allow_access_to_unprotected_subobjects__` is a bit of a sledge hammer here, but I can't see any way of getting to such a `macros` object without hitting all necessary security checks before you even get close. Attempts to install a `ClassSecurityInfo` on the class and declaring e.g. `__getitem__` public didn't work.

Fix subscript access on Page Template `macros` attribute

---

docs/zdgbook/ObjectPublishing.rst

The text now reflects that the default encoding is UTF-8 (actually since 2011).

Revise "Character Encodings for Responses"

---

CHANGES.rst
constraints.txt
requirements-full.txt
sources.cfg
versions-prod.cfg

Fixes #516
All tests still pass. Those remaining references were most likely an oversight after the merge into ZCatalog.

Removed references to separate ``Products.ZCTextIndex``

---

docs/zdgbook/ObjectPublishing.rst

Especially, the section headers have been bumped, as they certainly
are no subsection of the preceeding "Controlling Base HREF".

Improve formatting.

---

docs/zdgbook/ObjectPublishing.rst

- fix referral to chapter about Acquisition
- wrap infos about Acquistion in a note paragraph
- delete confusing example
- fix docstrings in examples

Revise section "Traversal and Acquisition"

---

docs/zdgbook/ObjectPublishing.rst

- fix refeference to chapter "Security"
- do not mention ___bobo_realm__ as it is only valid for deprecated
ZServer setup and the realm topic will be covered later in the chapter

Revise section "Basic Publisher Security"

---

docs/zdgbook/ObjectPublishing.rst

- add links for further information about Acquisition
- fix references to other chapters

Revise section "Zope Security"

---

docs/zdgbook/ObjectPublishing.rst

... as they offer no relevant information.
Drop subsection testing.
As there is no information about the mentioned "builtin support" for
testing.
A link to the testing section is already in the table of contents.
Drop subsection "Publishable Module".
The introductory sentence says it all: "If you are using the Zope
framework, this section will be irrelevant to you."
Also see discussion about "ZPublisher for Zope vs own module", see
https://github.com/zopefoundation/Zope/pull/546#issuecomment-482854693

Drop some subsections.

---

docs/zdgbook/ObjectPublishing.rst

- fixed minor grammar problems
- improved formatting
- deleted note about not to use more than one method field, as
it is a common use case to create forms with several input buttons,
each with a method argument

Revise subsection "Method arguments"

---

src/App/dtml/manage_navbar.dtml
src/App/dtml/menu.dtml
src/Products/Five/utilities/browser/edit_markers.pt
src/zmi/styles/resources/zmi_base.css

Hi @dataflake, 
referring to #548 now the root link is added and zope.org link shifted into the sitemap popup. Moreover for #572 the control button spacing is monotonized. Both shown in the following screen image:

ZMI usability: ZMI root link, monotonized tab interface controls

---

zope-ecosystem.cfg

... as opposed to PythonScripts, with ExternalMethod it is also possible
to set a breakpoint, raise exceptions or - more general - use not only
a restricted set of Python syntax.
This make debugging and setting up special cases, e.g. to validate
Zope behaviour for the documenation overhaul much easier.

Extend zope-ecosystem.cfg by Products.ExternalMethod.

---

docs/zdgbook/ObjectPublishing.rst

For further information about the removal of support for FTP and
WebDAV please refer to:
WSGI as the new default server type
https://zope.readthedocs.io/en/latest/zope4/news.html#wsgi-as-the-new-default-server-type

Remove obsolete information about FTP and WebDAV.

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/interfaces.py
src/ZPublisher/tests/testHTTPRequest.py

This PR addresses #620.
It allows to control the use of Zope's internal XML-RPC for POST requests with Content-Type `text/xml` via the registration of a `ZPublisher.interfaces.IXmlrpcChecker` utility. If such a utility is registered, it is called for those candidate requests to decide whether or not this should really be handled via the internal XML-RPC support. Nothing changes, if no such utility is registered.

Optionally control internal xmlrpc use

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py

This PR fixes #630 by not caching the result of an implicit request lookup (in the form `request.get` or `request[...]` in contrast to `request.{form|cookies}{.get,[...]}`) in `other`.
There is a minor backward incompatibility affecting applications which might rely on finding form data/cookies in `other` after the first access.

Do not cache (implicit) request access to form data or cookies

---

CHANGES.rst
src/OFS/DTMLMethod.py
src/OFS/History.py
src/OFS/dtml/history.dtml
src/OFS/tests/testHistory.py
src/Products/PageTemplates/ZopePageTemplate.py

During Hanno's brutal cleanup he ripped out the ZMI History tab and functionality behind it. I would like to reintegrate it because it it very useful for those who edit scripts in the ZODB. Matter of fact, this functionality is critical for a customer of mine.
The code in this PR represents the last available revisions. It has been cleaned up to be Python 3-compatible, PEP-8 compliant, and the ZMI History template has been updated to look appealing on Zope 4.

Revive the removed History tab

---

CHANGES.rst
src/Zope2/utilities/skel/etc/zope.conf.in
versions.cfg

This pull request tries to follow through on #679.
As a first suggestion I have just removed the recommendation of tempstorage from the generated config file. Since this is maybe impractical, an alternative suggestion could be to reformulate the commented out snippet like this:
```
```
However, I do not pretend to understand the ramifications of this recommendation (nor have I tested it in depth), so I am putting it here as a discussion point.

Remove recommendation of tempstorage.

---

requirements-rtd.txt
setup.py

This tries to fix #668 by removing further `tempstorage` dependencies.
I am pretty sure that just removing `tempstorage` from the `[docs]` section of extras require is pretty safe as I can't find any mention of `tempstorage` in the documentation. I am a bit more hesitant about the requirements.rtd.txt - but am pretty sure that this is also not required.
Feedback welcome.

Remove further tempstorage dependencies.

---

CHANGES.rst
src/Products/SiteAccess/VirtualHostMonster.py
src/ZPublisher/HTTPRequest.py

Fixes #683 
The behavior of the zope.publisher version is slightly different, so for the VirtualHostMonster code it was not a full drop-in replacement.

Reuse ``zope.publisher.http.splitport`` instead of defining our own

---

docs/zdgbook/ComponentsAndInterfaces.rst
docs/zdgbook/GettingStarted.rst
docs/zdgbook/ObjectPublishing.rst
src/OFS/tests/testProperties.py
src/ZPublisher/tests/testHTTPResponse.py

Grep for `Python 2` and fix the places where it was used.

---

CHANGES.rst
src/Products/SiteAccess/VirtualHostMonster.py
src/Products/SiteAccess/tests/testVirtualHostMonster.py

Fix VirtualHostMonster not being able to set mappings under Python 3.

---

CHANGES.rst
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

Set REMOTE_USER in wsgi publisher for next apps in wsgi pipeline. 
e.g. useful for have user in access logs, ...

Set ``REMOTE_USER`` in wsgi environ using Zope user authentication

---

CHANGES.rst
src/Shared/DC/Scripts/Bindings.py

Fixes #703 
Only "drawback" is that none of that code is tested. But the issue is obvious and correctly identified by Dieter.
This PR is against `master`/Zope 5. I can do a backport to `4.x` if it is accepted.

Fix ``__getattr__`` signature in ``UnauthorizedBinding``

---

src/ZPublisher/BaseResponse.py

modified:   src/ZPublisher/BaseResponse.py

Format docstrings in a consistent way.

---

src/OFS/dtml/properties.dtml
src/zmi/styles/resources/zmi_base.css
src/zmi/styles/resources/zmi_base.js

Hi @dataflake, 
these changes in addition to
https://github.com/zopefoundation/Zope/pull/731
It fixes a floating problem wide screens with src/OFS/dtml/properties.dtml, the table title text alignment of the permissions table and pushes the safari to the compressed view (safari has an known issues with browser window width)
Cheers
f

ZMI: permission table compressed for safari

---

CHANGES.rst
src/OFS/interfaces.py

Fix broken deprecated import when ZServer is not installed

---

CHANGES.rst
buildout.cfg
docs/INSTALL.rst
setup.py

Otherwise Zope won't start up when installed with `pip` and the `constraints.txt` file.
When accepted this PR should also be ported to the 4.x branch.
Relates to #734.

Add missing Paste dependency.

---

CHANGES.rst
src/Zope2/Startup/serve.py

Close opened database connections during shutdown. 
That's important at least with Relstorage, where ZODB cache is saved persistently on filesystem within db closing, with a great improvement on startup.
Here where ZServer do something like this: https://github.com/zopefoundation/ZServer/blob/master/src/ZServer/Zope2/Startup/starter.py#L112

close opened db during shutdown

---

version_ranges.cfg

Version 6 and higher no longer work on Python 2.7, so you get a SyntaxError when running buildout.
(I am looking at Zope 2.13 because the Plone hotfix of this week should be merged in parts of Zope. But the Zope(2) package itself does not seem affected. Still, would be nice if the buildout can finish.)

Pin more-itertools to less than 6.0.0. [2.13]

---

docs/zopebook/InstallingZope.rst

- added NGINX, removed IIS as a "popular web server"
- fixed several typos
- fixed the link to the virtual hosting chapter
- removed broken links how to configure IIS
- added information about Waitress
modified:   docs/zopebook/InstallingZope.rst

Update section about using Zope with a web server

---

docs/maintenance.rst

Running `bin/checkversions` with  `--level=2` does not list packages with updated major versions. E. g. it does not list `mock 4.x`.

Prevent updating to Python 3 only versions.

---

.travis.yml

Without this changes even `pip --version` fails because it cannot import `pip`. 😞

Fix pip on Travis

---

docs/zdgbook/Security.rst

As discussed in #770, the "docstring restriction" when publishing objects is not really part of the security policy stuff. But it is at least related, so I decided to mention it in the security chapter in 2 places which are likely to be read.

Try to hide the docstring restriction a little less.

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

Backport of #830 to the 4.x branch

Improve solidity of the ``debugError`` method (4.x)

---

src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py
src/ZPublisher/tests/test_WSGIPublisher.py

Refs. #829
Also takes care of the `WSGIResponse.debugError` method that was not tested at all.

Increase test coverage and extend the fix for #829 also for the WSGI

---

CHANGES.rst
docs/zopebook/AppendixC.rst
src/Products/PageTemplates/engine.py
src/Products/PageTemplates/tests/testC2ZContext.py
src/Products/PageTemplates/tests/testExpressions.py
src/Products/PageTemplates/tests/testVariables.py

This fixes #860 as far as ``chameleon`` allows it.
As "https://github.com/malthe/chameleon/issues/323" demonstrates, `chameleon` currently supports `attrs` only in `tal:content` but not in `tal:define` nor in `tal:replace`. This PR allows the use of the predefined page template variable `attrs` at locations where `chameleon` supports it; if used at other places, `attrs` has the value `None`. The code should continue to work after the `chameleon` problem is fixed - but some cleanup would be possible after that.
The PR also removes the mentioning of `CONTEXTS` as predefined page template variable from the Zope Book as no template engine (neither `zope.pagetemplate`nor `chameleon`) implements it. It adds tests for the remaining predefined variables.

Restore "attrs" template variable support

---

CHANGES.rst
buildout.cfg
src/Products/PageTemplates/tests/input/switch.html
src/Products/PageTemplates/tests/output/switch.html
src/Products/PageTemplates/tests/testHTMLTests.py

This PR adds a test for `tal:switch` in relation to #862 .
Note that the test requires a new (upcoming) `chameleon` version to succeed. Do not merge until this version is used by `Zope`.

add test for `tal:switch` - to verify #862

---

CHANGES.rst
docs/zopebook/AdvZPT.rst
docs/zopebook/ZPT.rst
src/Products/PageTemplates/Expressions.py
src/Products/PageTemplates/tests/testExpressions.py
src/Products/PageTemplates/unicodeconflictresolver.py

This PR is one possible implementation for "https://github.com/zopefoundation/Zope/issues/863".
It interprets "some builtins" as:
* in an untrusted context: the builtins from `AccessControl.safe_builtins`
* in a trusted context: all Python builtins and those from `AccessControl.safe_builtins`
Thus, the set of allowed builtins is likely larger than that natively supported by `chameleon`. I believe that `chameleon` currently does not expose its set for external access; this would be necessary to ensure that the same set of builtins is supported.

allow (some) builtins as first element in a path expression

---

CHANGES.rst
src/Products/PageTemplates/Expressions.py
src/Products/PageTemplates/engine.py
src/Products/PageTemplates/expression.py
src/Products/PageTemplates/interfaces.py
src/Products/PageTemplates/tests/testZopeAwareEngine.py

This PR addresses #864 .
It defines a new interface `Products.PageTemplates.interfaces.IZopeAwareEngine` which conceptionally is a marker indicating that a TALES engine has a `Zope` compatible `PathExpr`.
The PR marks the "Engine" classes defined by `Products.PageTemplates` with `IZopeAwareEngine` even though Zope awareness is not a property of the class but of the individual instances and their `PathExpr`. The motivation here is that components which derive from or instantiate those classes are likely providing a Zope compatible `PathExpr`.
`IZopeAwareEngine` can be used as the `provides` of an adapter registration in order to adapt a non `IZopeAwareEngine`. An adapter registered in this way is used only for engines which do not provide `IZopeAwareEngine` by themselves (currently, …

`IZopeAwareEngine` to address #864

---

src/Products/PageTemplates/tests/testChameleonTalesExpressions.py
src/Products/PageTemplates/tests/testZopeTalesExpressions.py

https://github.com/zopefoundation/zope.testrunner/issues/108
has caused that each test from `HTMLTests` was executed 3 times. Avoid this unnecessary (though harmless) repeated test execution.
The change is cosmetic only -- therefore, not described in `CHANGES.rst`.

avoid repeated execution of the same `HTMLTests`

---

CHANGES.rst
src/Products/PageTemplates/engine.py
src/Products/PageTemplates/tests/testZopePageTemplate.py

This should fix https://github.com/plone/Products.CMFPlone/issues/3145
`Products.PageTemplates.Expressions.ZopeContext` has provisions for so called "Unicode Conflict Resolution", i.e. logic to convert bytes to unicode. This was never supported for `chameleon` (which uses its own independent logic for this case).
Due to a bug, it became not available with the combination of `zope.tales` and `chameleon`. This bug is fixed by this PR and now "Unicode Conflict Resolution" is available for `chameleon` rendering as well.
The "Unicode Conflict Resolution" relies on extensions by `ZopePageTemplate`, it does not work for a raw `PageTemplate`.

make "Unicode Conflict Resolution" available for `chameleon` rendering

---

CHANGES.rst
src/Products/PageTemplates/Expressions.py
src/Products/PageTemplates/tests/input/UnicodeResolution.html
src/Products/PageTemplates/tests/output/UnicodeResolution.html
src/Products/PageTemplates/tests/testHTMLTests.py
src/Products/PageTemplates/tests/util.py

Previously, the "unicode conflict resolution" integration (needlessly) relied on `contexts` containing `context`. While this is guaranteed for `ZopePageTemplate` this is usually not the case for a raw `PageTemplate`.
This PR removes the restriction.

let "unicode conflict resolution" work for all templates

---

CHANGES.rst
src/Products/PageTemplates/engine.py
src/Products/PageTemplates/tests/testC2ZContext.py

This PR improves the faithfulness of the "chameleon zope context wrapping".
`chameleon` evaluates TALES expressions in a do called `Scope` -- a mapping from (variable) names to their current values.
`zope.tales` TALES expressions are functions returning a value when called with a "context". The "context" is expected to know about the current name to value mapping and to know the TALES engine. The precise details of the "context" are determined by the TALES engine.
The "chameleon zope context wrapper" integrates `chameleon`'s `Scope` and `zope.tales`' "context" into one object. Its task is to manage variable settings in the `Scope` and everything else in the "context".
Formerly, the wrapper delegated data to the correct subobjects; but it took much of its implementation directly from …

make "chameleon zope context wrapping" more faithfull

---

CHANGES.rst
src/Products/PageTemplates/engine.py
src/Products/PageTemplates/tests/testTranslation.py

This PR fixes #876 
When a template is compiled by `chameleon` expressions are represented in the following execution by `chameleon.tokenize.Token`s, when the template code comes from the `chameleon` cache, expressions are represented in the execution by simple text. The `zope.tales` integration has been partially type preserving: in some cases a `Token` input resulted in a `Token` output. Under Python 3, `chameleon` interprets a `Token` result wrongly as "to be translated". The result has been unsolicited translations when a template was compiled by the current process and correct translations when the template came from the cache.
This PR works around this behavior by explicitly converting `Token` into `str` under Python 3.

avoid unsolicited translations

---

src/Products/PageTemplates/engine.py

Until @malthe 's comment in "https://github.com/zopefoundation/Zope/pull/878#issuecomment-662724293", I did not really understand the cause of #876 (and as a consequence blamed `chameleon` wrongfully to be part of the problem).
This is an improved PR to fix #876 based on the insight gained by the comment above.

improve unsolicited translation avoidance

---

versions.cfg

Needed for ZODB 5.6.0.
After this, I think we are ready for a Zope 4.5.1 release.

Upgrade zodbupdate to 1.5. [4.x]

---

sources.cfg

The master branch targets Zope 5.
It fails with python 2.7:
```
File "/Users/maurits/community/plone-coredev/5.2/src/DocumentTemplate/src/DocumentTemplate/DT_Var.py", line 156, in <module>
import urllib.parse
ImportError: No module named parse
```

Zope 4: use DocumentTemplate branch 3.x.

---

src/ZTUtils/__init__.py

ZTUtils.LazyFilter could not be imported inside a restricted python script due to this missing coma.

Bugfix: missing coma so security declaration was not ok.

---

CHANGES.rst
src/OFS/SimpleItem.py
src/OFS/tests/testSimpleItem.py

Override `id` in `OFS.SimpleItem.Item_w__name__` to avoid bugs by use of deprecated direct `id` access (--> #903 ).
In ancient days, all Zope objects had an `id` attribute. With the advent of Zope 3 technologies, `__name__` seemed a better name for the name/id of a Zope object: direct `id` access was deprecated in favor of `getId()` and `getId` was defined to switch between `id` and `__name__`, as necessary. For backward compatibility `__name__` was defined as alias for `id`, overridable on the instance level. This allowed for a graceful migration from the old `id`  to the new `__name__` use in the context of existing Zope object without `__name__` but with `id`. However, newly created `Item_w__name__` instances had a wrong `id`: for them, the deprecated direct access to `id` led to bugs …

Senseful "OFS.SimpleItem.Item_w__name__.id" definition

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

HTTP requires that response (and request) header fields use `ISO-8859-1` (or a subset) as charset for their values. `waitress` builds on this and raises an exception when a field value cannot be represented in this charset.
This PR provides support for RFC 2047 ("encode_words") and RFC 2231 ("encode params"; in its HTTP specialization by RFC 5987/8187) for response header field values not covered by `ISO-8859-1` via new `ZPublisher.HTTPResponse.header_encoding_registry` (of class `HeaderEncodingRegistry`). `HTTPResponse.listHeaders` consults this registry in its `listHeaders` method to determine how header field values outside `ISO-8859-1` should be handled. By default, it uses `encode_params` as encoding for `Content-Type` and `Content-Disposition` and does not encode other header fields …

Http response header encoding

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

* cosmetics: work around XEmacs highlighting bug
* HTTP response header encoding support
* reference PR in `CHANGES.rst` (for documentation purposes)
* fix typo
* Revert "cosmetics: work around XEmacs highlighting bug"
This reverts commit e4749c987cae9853f9f8b72ab1df9bcd1792257a.

Http response header encoding (#905)

---

CHANGES.rst
src/App/ApplicationManager.py
src/App/CacheManager.py
src/App/DavLockManager.py
src/App/dtml/davLockManager.dtml
src/App/dtml/debug.dtml
src/App/tests/test_ApplicationManager.py
src/App/tests/test_cachemanager.py
src/ZPublisher/WSGIPublisher.py

Fixes #898 
This PR adds a "Debug Information" page to the control panel. This Debug Information page restores those parts of the old Zope 2  DebugInfo page that are not already presented on other control panel tabs.
The trickiest part was finding a place to add the request debugging information for running requests that shows up at the bottom of the page where the database connection information is. I have added it inside the WSGI publisher code. This used to be done by the `App.ZApplication.ZApplicationWrapper.__bobo_traverse__`, but that method is only called by the old ZServer publisher.
The ZMI bits could use some prettification, but functionally it's all there.

Restore the ZMI `Debug Information` control panel page

---

docs/news.rst

... as WebDAV was restored for Zope.

Do not point to ZServer for WebDAV support

---

CHANGES.rst
src/Products/PageTemplates/engine.py
src/Products/PageTemplates/tests/input/InterpolationInContent.html
src/Products/PageTemplates/tests/output/InterpolationInContent.html
versions-prod.cfg

Fixes #925 
The `chameleon` interpolation has special characters `${}`. When those characters are usable in TALES path expressions, `chameleon`'s interpolation heuristics (use the longest possible interpolation string the compilation of which does not cause a syntax error) has a high risk to break. One such example is #925 
This PR (essentially) forbids the use of `${}` in path expressions to reduce the failure risk for the interpolation heuristics (actually, it forbids those characters only in `SubPathExpr`s with a standard path; they can still be used in other types, e.g. a trailing `python` or `string` expression).

Exclude ${} from use in TALES path expressions

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

Apparently (--> "https://github.com/zopefoundation/Zope/pull/905#issuecomment-726018560"), `waitress` insists on native strings as values for HTTP response headers and rejects `unicode` values on Python 2.
Looking into this problem, I noticed that under Python 3 `bytes` header values are not handled correctly (this time by `ZPublisher.HTTPResponse._scrubHeader`).
This PR ensures proper use of native strings as HTTP response header values converting via `ISO-8859-1` if necessary.

Ensure native string response headers

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

I created a PR for this backport because it required an additional fix in response handling that I need some eyes on. The fix only affects Python 2 where the `setBody` method receives a body of type `io.BytesIO` sometimes, and the code would misinterpret that as one of the objects to raise the `NotFound`

Port of #933 to 4.x

---

CHANGES.rst
src/App/dtml/cpConfiguration.dtml
src/App/dtml/debug.dtml
src/App/dtml/undo.dtml

hi @icemac,
i added some missing style to the ZMI of the debug-info page and montonized the look:
Thanks for taking at look at it
f

zmi: added styles to debug info, minor fixes

---

appveyor.yml
tox.ini

We still need easy_install (removed in setuptools 52) to install packages which have no wheels.

Fix AppVeyor

---

CHANGES.rst
src/OFS/ObjectManager.py

The ``compute_size`` method properly returns None if the content does not  have a ``get_size`` method but the parent has.
Refs #948

[4.x] Backport fixes for the ``compute_size`` method

---

.gitignore
src/zmi/styles/resources/zmi_base.css

Hi @icemac ,
here is a small css fix for rendering the SQL code in the Test menu:
And  I added .vscode to the git-ignored folders.
Cheers
f

Fixed css of html code element height

---

CHANGES.rst
MANIFEST.in
src/ZPublisher/tests/test_xmlrpc.py
src/ZPublisher/xmlrpc.py

Fixes #954 
This PR attempts to detect attributes that are Zope objects during creation of an XML-RPC object dump and enforce at least the `View` permission on them.

Enforce Zope permissions for recursive XML-RPC data dumps

---

src/ZPublisher/tests/test_Converters.py

The intention for this test is obsolete since we are on Python 3.
And especially after applying pyupgrade via
https://github.com/zopefoundation/Zope/commit/5bfcac7fc0c5a620326955571fc69f20e106a884
the deleted test duplicated test_field2string_with_string.

Remove obsolete test

---

CHANGES.rst
setup.py
src/ZPublisher/Converters.py
src/ZPublisher/tests/test_Converters.py

Until now field converters could be applied on files with unclear outcome.
The problems with trying to convert files to text (detect MIME type, guess charset...)
were discussed in length in https://github.com/zopefoundation/Zope/issues/558#issuecomment-485064104.
Handling files only makes sense for the `field2bytes` converter.
This fixes #558

field2* converters should not handle files

---

CHANGES.rst
setup.py
src/Products/PageTemplates/Expressions.py
src/Products/PageTemplates/expression.py
src/Products/PageTemplates/tests/input/CheckPathTraverse.html
src/Products/PageTemplates/tests/output/CheckPathTraverse.html
src/Products/PageTemplates/tests/testChameleonTalesExpressions.py
src/Products/PageTemplates/tests/testExpressions.py
src/Products/PageTemplates/tests/testHTMLTests.py

This PR applies the traversal fixes from `master` on the `4.x` branch. I also bumped the version number to 4.6 because this is a behavior change.

Fix traversal behavior for 4.x

---

src/zmi/styles/resources/zmi_base.css

hi @dataflake ,
just a tiny css fix for the copyright page: 
on that page the header had some margins. 
Now it is "in line" and typography is more consistant:
Best regards
f

fixed header spacing of copyright page

---

CHANGES.rst
src/Products/PageTemplates/Expressions.py
src/Products/PageTemplates/expression.py
src/Products/PageTemplates/tests/testExpressions.py
src/Products/PageTemplates/tests/testHTMLTests.py

This PR backports the stricter traversal checks from Zope 5 to Zope 4 to prevent additional obscure traversal failures. Plone monkey patches the methods already so it's safe to be stricter in Zope itself.

Backport stricter traversal checks from Zope 5

---

CHANGES.rst
docs/zdgbook/ObjectPublishing.rst
setup.py
src/App/tests/testManagement.py
src/OFS/tests/testProperties.py
src/ZPublisher/Converters.py
src/ZPublisher/tests/testHTTPRequest.py
src/ZPublisher/tests/test_Converters.py

After dropping Python 2, there is no more use of `unicode` converters.
This means, after a deprecation period, that e.g. field2utext will be
removed and only field2text should be used any more.
P.S.: This PR currently fails - for reasons see https://github.com/zopefoundation/Zope/issues/962#issuecomment-835357220
Also, please keep the discussion in https://github.com/zopefoundation/Zope/issues/962

Deprecate usage of `unicode` converters

---

CHANGES.rst
src/OFS/DTMLMethod.py
src/OFS/tests/test_DTMLMethod.py

See https://github.com/zopefoundation/Products.PythonScripts/issues/50
It makes no sense that "Manager" users can effectively be prevented from modifying a DTML Method or DTML Document with a proxy role the Manager-level user doesn't have. This PR circumvents the proxy role check for Manager users.
This also utilizes the cleaner implementation of `_validateProxyRoles` from `Products.PythonScripts`.

Make sure "Manager" users can always modify proxy roles

---

CHANGES.rst
src/ZPublisher/tests/test_utils.py
src/ZPublisher/utils.py

You can call this to fix lines properties to only contain strings, not bytes.
It also replaces the deprecated property types ulines, utext, utoken, and ustring with their non-unicode variants.
See https://github.com/zopefoundation/Zope/issues/987 for why this is needed.
Note: the code is not called by Zope itself. The idea is that integrators who think they need this in their database, can call it.
Sample use:
app.ZopeFindAndApply(app, apply_func=fix_properties)
I intend to use this (or a temporary copy) in the Plone 6 upgrade code.
See https://github.com/plone/Products.CMFPlone/issues/3305
I tried it on a few databases, and it works there, although only very little is changed.

Add function ZPublisher.utils.fix_properties.

---

CHANGES.rst
src/OFS/dtml/properties.dtml
src/OFS/tests/export.xml
src/Products/PageTemplates/ZopePageTemplate.py
src/ZTUtils/Zope.py

- Zope PageTemplate still created a title property with type ustring.
Strangely, after this commit, for existing Page Templates it is automatically a string, without needing to change anything.
- OFS tests had an export.xml with a ulines.
- ZTUtils/Zope.py had unreachable code that used ustring:
the condition `if isinstance(v, str)` was already handled a few lines up
Also, in the properties form, show deprecation for ulines, utext, utokens, ustring.
Add a link to https://github.com/zopefoundation/Zope/issues/962 where they got deprecated.
Note: you can still add these properties in this form.
I would almost be inclined to remove them, but we should probably keep them in Zope 5.

Remove deprecated ulines, utext, utokens, ustring from more code.

---

CHANGES.rst
src/webdav/NullResource.py
src/webdav/tests/testPUT_factory.py

Fixes #997 partially
This PR allows a WebDAV PUT factory to change a new object ID to something other than the `PUT` URL target name.

Enable WebDAV PUT factories to change a newly created object's ID

---

CHANGES.rst
src/Products/PageTemplates/PageTemplateFile.py
src/Products/PageTemplates/ZopePageTemplate.py
src/webdav/NullResource.py
src/webdav/tests/testPUT_factory.py

Fixes #997 content guessing
The PR adds content type guessing purely by file name extension if the generic `application/octet-stream` content type is passed in. It also fixes up Page Template issues with content type guessing.

Improve type guessing for the default WebDAV PUT factory

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

Response data that has no `__bytes__` method but a `__str__` method,
like lists, dicts and similar, can now be handled by the publisher as it
was handled in Zope 2, by returning the string representation.
Fixes https://github.com/zopefoundation/Zope/issues/1006

Use string representation of response data

---

CHANGES.rst
src/ZPublisher/tests/test_utils.py
src/ZPublisher/utils.py

I created this function in Zope 5.4 and it worked for the databases I tried it on.
But on another project I ran into several exceptions.
See tracebacks in Plone:
https://github.com/plone/plone.app.upgrade/issues/270
Note that `plone.app.upgrade` has a temporary copy of the same function.
I fixed the function there as well today:
https://github.com/plone/plone.app.upgrade/pull/271

Fix several exceptions when calling ZPublisher.utils.fix_properties.

---

CHANGES.rst
src/Testing/ZopeTestCase/testFunctional.py
src/Testing/ZopeTestCase/zopedoctest/FunctionalDocTest.txt
src/Testing/tests/test_testbrowser.py
src/ZPublisher/HTTPRequest.py
src/ZPublisher/HTTPResponse.py
src/ZPublisher/cookie.py
src/ZPublisher/interfaces.py
src/ZPublisher/tests/testHTTPResponse.py
src/ZPublisher/tests/test_cookie.py

fixes #600 and #1008.
This PR introduces two cookie related policies, `ICookieParamPolicy` and `ICookieValuePolicy`, and a cookie parameter registry.
The cookie policies allow customization of cookie handling. Details can be found in `ZPublisher.interfaces`.
Cookie parameter customization may be helpful  for some applications  wanting to support embedding in foreign sites because recent browser versions use `Lax` as default for the `SameSite` cookie parameter. As a consequence cookies are no longer delivered to applications embedded in a foreign site unless their definition carries the parameters `SameSite=None; Secure`.
The default cookie parameter policy automatically adds a missing `Expires` if the `Max-Age` parameter is present (to support HTTP/1.0).
The current cookie standard (i.e. …

enhanced cookie support

---

CHANGES.rst
src/OFS/Image.py
versions.cfg

Fixes #1015.
This PR essentially documents that `OFS.Image.File._read_data` returns a tuple *data*, *size* with *data* either a `bytes` or `Pdata` instance. Based on this assertion, it can simply drop the buggy code in the `PUT` method referred to in #1015.
@arnaud-fontaine could you please verify if this PR resolves your issue.

fix `OFS.Image.File.PUT` -- Issue 1015

---

versions.cfg

The previous commit updated `tqdm` (some command line progress bar thingie) to 4.63.0, which has `importlib-resources` as new requirement. This was not pinned yet. So Plone coredev 5.2 locally failed on Python 2.7 with the latest Zope 4.x dev versions.
Also added pin for `singledispatch`, which is required by `importlib-resources`. Latest version seems fine.
Note: I am also fixing this temporarily in Plone coredev. But since these packages are pulled in by `tqdm` which is already pinned in Zope, it makes sense to add the pins here.

Add pin for last version of importlib-resources that works on Python 2.

---

sources.cfg

The git protocol was disabled a few weeks ago.

Updated sources.remotes.github from git protocol to https. [master]

---

CHANGES.rst
README.rst
buildout.cfg
constraints.txt
docs/INSTALL.rst
docs/wsgi.rst
requirements-full.txt
versions-prod.cfg

This PR backports new Python version-dependent waitress version pins to the 4.x branch.
I have not ported the requirements file generator script as that's completely incompatible with Python 2 now and I have removed its invocation in `buildout.cfg`. I am inclined to remove that script on this branch and manually maintain the requirements files instead, that seems less work than porting the convenience script.

backport waitress version pins to Zope 4

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

Fixes #1027.
All components of a redirect URL are properly quoted (not just the path component).

quote all components of redirect URL (not only path)

---

CHANGES.rst
constraints.txt
requirements-full.txt
versions-prod.cfg

Testing Zope products on Python 3.5 breaks because DocumentTemlate 4 cannot be installed because of version constraints.
In https://github.com/zopefoundation/Products.PluggableAuthService/runs/6146524828?check_suite_focus=true we get:
```
Version and requirements information containing documenttemplate:
[versions] constraint on documenttemplate: 4
Requirement of Zope>=4.2.1: DocumentTemplate<4.0,>=3.0
Requirement of Zope>=4.0b5: DocumentTemplate<4.0,>=3.0
Requirement of Zope>=4.0b4: DocumentTemplate<4.0,>=3.0
Requirement of Products.ZCatalog: DocumentTemplate
Requirement of Products.PythonScripts: DocumentTemplate
While:
Installing test.
Error: The requirement ('DocumentTemplate<4.0,>=3.0') is not allowed by your [versions] constraint (4)
```
This also happens locally.
I do not fully …

4.x: Fix version pin specifications for Python 3.5 compatibility.

---

CHANGES.rst
src/ZPublisher/cookie.py
src/ZPublisher/tests/testHTTPResponse.py
src/ZPublisher/tests/test_cookie.py

If the value of the `domain` attribute in the cookie starts with `.` Zope currently breaks.
But according to https://www.rfc-editor.org/rfc/rfc6265#section-4.1.2.3 it should be allowed.
I added a test and a fix, without the fix the new test breaks with:
```
Error in test test_domain (ZPublisher.tests.test_cookie.CookieParameterRegistryTests)
File "/.../lib/python3.7/unittest/case.py", line 59, in testPartExecutor
yield
File "/.../lib/python3.7/unittest/case.py", line 628, in run
testMethod()
File "/.../Zope/src/ZPublisher/tests/test_cookie.py", line 150, in test_domain
_, v = convertCookieParameter("domain", ".zope.dev")
File "/.../Zope/src/ZPublisher/cookie.py", line 152, in convert
return nn, (value if value is None else self[nn](value))
File …
```

Strip leading `.` from cookie domain names.

---

src/Shared/DC/Scripts/Signature.py

`_setFuncSignature` was accidentally setting `__code__` and
`__defaults__` twice.
On Zope 4 it should also support the old python 2 names `func_code`
and `func_defaults`, because Zope 4 supports python 2
Fixes https://github.com/zopefoundation/Products.PythonScripts/issues/55

Scripts/Signature: keep setting func_code and func_defaults

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/cookie.py
src/ZPublisher/tests/test_cookie.py

Fixes #1052.
RFC 6265 section 5.1.4 ("https://www.rfc-editor.org/rfc/rfc6265#section-5.1.4") specifies how browsers should match the cookie path parameter to the request URI: it does not involve unquoting. As a consequence it is vital that the quoting used in the URL construction and in the cookie path computation is identical.
Zope (--> `OFS.Traversable`) uses Python's `urllib.parse.quote` as the usual URL quoting. This quotes all special characters with the exception of `-_./`. To match the requirement of the preceding paragraph for the standard case of an URL path, the cookie path handling, too, uses `quote` as its quoting. A check tried to ensure that partially quoted path values are rejected: if a path value contains `%` (indication that is is partially quoted), it must not contain …

fix cookie path parameter handling --> #1052

---

README.rst

It is not telling the truth for Python versions > 3.6.
Fixes #1051.

Remove requirements badge

---

versions-prod.cfg
versions.cfg

Had to add some version pins needed for different Python versions so buildout could run seccessfully. (Checked with all supported Python versions.)

Upgrade to zope.dottedname 5.0 where possible.

---

CHANGES.rst
src/Testing/ZopeTestCase/functional.py
src/Testing/ZopeTestCase/testFunctional.py
src/Testing/ZopeTestCase/zopedoctest/functional.py

Fixes #1058
This applies to `Testing.ZopeTestCase.FunctionalTestCase.publish` and `html` from zopedoctest, both were using Zope's WSGI application, but were not preparing `PATH_INFO` in environ like a WSGI server is supposed to do.
As a result, it was not possible to use these utility with %-encoded paths or paths with non-ascii characters.
This fixes the issue by encoding the PATH_INFO and also changes the internals a bit not to pass a request, but using the request factory, so that the request environ is also set by WSGIPublisher, which does its own handling of encoded paths.

Testing: make `publish` utility functions handle PATH_INFO

---

CHANGES.rst
src/ZPublisher/tests/testHTTPRequest.py
src/ZPublisher/utils.py

Fixes #1061
Basic authentication header charset is unspecified, but in practice these days user agents use UTF-8.

ZPublisher/utils: fix encoding in basic_auth_encode and basic_auth_decode

---

CHANGES.rst
src/ZPublisher/tests/testHTTPRequest.py
src/ZPublisher/utils.py

Fixes #1062
and backports #1063 for 4.x
Basic authentication header charset is unspecified, but in practice these days user agents use UTF-8.
On python 2 we also don't want basic_auth_encode to encode the str because we don't expect an unicode but a native string.

Zope4: ZPublisher/utils: fix encoding in basic_auth_encode and basic_auth_decode

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

This tells user agents that we expect the user-pass to be UTF-8 encoded, as per section "2.1.  The 'charset' auth-param" of RFC7617.
https://datatracker.ietf.org/doc/html/draft-ietf-httpauth-basicauth-update-07#section-2.1

Use UTF-8 charset for WWW-Authenticate headers in challenge responses

---

CHANGES.rst
docs/operation.rst
src/Zope2/utilities/adduser.py

Script `addzopeuser` accepts now parameter '-c' or '--configuration'. This allows passing in an custom location for the `zope.conf` file to use. If not specified behavior not altered.
On you request @pbauer 
I found it was possible already to specify the path setting an environment variable `ZOPE_CONF`. But I think it is more intuitive to pass it as a parameter.
While at it and because it simplifies the code and auto-documents the script I introduced usage of argparse here.

addzopeuser accepts custom location of zope.conf

---

CHANGES.rst
docs/zdgbook/ObjectPublishing.rst
src/App/Management.py
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

* drop implicit detection of content type
* drop support for returning HTML with ``response.setBody((title, body))``

HTTPResponse: default content type to text/plain

---

docs/INSTALL.rst

plone.recipe.zope2instance needs eggs to be defined, otherwise it tries to install an egg with the name as the section name, which in the case of `zopeinstance` does not exist.
Installing zopeinstance.
Couldn't find index page for 'zopeinstance' (maybe misspelled?)
Getting distribution for 'zopeinstance'.
Couldn't find index page for 'zopeinstance' (maybe misspelled?)
While:
Installing zopeinstance.
Getting distribution for 'zopeinstance'.
Error: Couldn't find a distribution for 'zopeinstance'.

INSTALL: fix example with plone.recipe.zope2instance

---

CHANGES.rst
src/App/Dialogs.py
src/App/tests/testManagement.py
src/App/tests/test_Dialogs.py
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

Now that Zope uses text/plain by default, MessageDialogs were served as text/plain. Keep compatibility by returning a special string with `asHTML` method, that ZPublisher.HTTPResponse.HTTPResponse.setBody understands.
MessageDialogs are deprecated and do not integrate well in Zope >= 4 ZMI, but they are used in some old products.

Serve MessageDialogs and exception views as text/html (4.x)

---

CHANGES.rst
src/App/Dialogs.py
src/App/tests/testManagement.py
src/App/tests/test_Dialogs.py
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

Now that Zope uses text/plain by default, MessageDialogs were served as text/plain. Keep compatibility by returning a special string with `asHTML` method, that ZPublisher.HTTPResponse.HTTPResponse.setBody understands.
MessageDialogs are deprecated and do not integrate well in Zope >= 4 ZMI, but they are used in some old products.
Fixes issues discussed in https://github.com/zopefoundation/Zope/pull/1079#issuecomment-1356246105

Serve MessageDialogs and exception views as text/html

---

CHANGES.rst
src/OFS/History.py
src/OFS/tests/testHistory.py

Fixes the problem described on https://bugs.launchpad.net/zope2/+bug/735999 that still happens when comparing history of `Products.PythonScripts.PythonScript` created with an old script magic or python magic.

History: support classes modifying instances in __setstate__ 

---

CHANGES.rst
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

No Content-Type text/html on empty exception views [master]

---

src/OFS/tests/testChownRecursive.py
src/OFS/tests/testTraverse.py
src/OFS/tests/test_Uninstalled.py
src/Products/Five/browser/tests/pages.txt
src/Products/Five/browser/tests/security.pt
src/Products/Five/browser/tests/test_pages.py
src/Products/PageTemplates/tests/testZopePageTemplate.py
src/Products/PageTemplates/tests/test_engine.py
src/Products/PageTemplates/tests/test_pagetemplate.py
src/Products/PageTemplates/tests/test_persistenttemplate.py
src/Products/PageTemplates/tests/test_viewpagetemplatefile.py
src/Testing/ZopeTestCase/testBaseTestCase.py
src/Testing/ZopeTestCase/testFunctional.py
src/Testing/ZopeTestCase/testInterfaces.py
src/Testing/ZopeTestCase/testPlaceless.py
src/Testing/ZopeTestCase/testPortalTestCase.py
src/Testing/ZopeTestCase/testSkeleton.py
src/Testing/ZopeTestCase/testZODBCompat.py
src/Testing/ZopeTestCase/testZopeTestCase.py
src/Testing/ZopeTestCase/zopedoctest/testAuthHeaderTest.py
src/Testing/ZopeTestCase/zopedoctest/testFunctionalDocTest.py
src/Testing/tests/test_testbrowser.py
src/Zope2/App/tests/test_startup.py

See #1091 - Fixes at least those parts that are triggered by Zope itself.

Get rid of DeprecationWarnings during unit tests

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

fixes #1095.
Primarily taken from #648.
The tainting logic has been incredibly complex and spread all over `ZPublisher.HTTPRequest.HTTPRequest.processInputs`. The PR takes it out of `processInputs` and centralizes it in the function `taint`. Doing so allows to work with the final results only not also with intermediate results.

Sanitize tainting

---

src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

Without this change, some tests (and possibly live code) in Plone fail because they do not pass the new required `charset` parameter. See https://github.com/plone/buildout.coredev/pull/844
And see discussion that I just started here:
https://github.com/zopefoundation/Zope/pull/1094#issuecomment-1459047253
Also fixes an unclosed file in a test.

FileUpload: use default encoding as charset when nothing is passed.

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

This PR fixes a problem reported in
https://github.com/plone/buildout.coredev/pull/844#issuecomment-1461044889
Apparently, `jquery` uses not standard conform content types of the form
`application/x-www-form-urlencoded; charset=utf-8`. With the switch from `cgi.FieldStorage` to `multipart`, `Zope` no longer recognized not standard `application/x-www-form-urlencoded` content type headers. As a result, some Plone tests broke.
This PR supports the `charset` parameter for `application/x-www-form-urlencoded`.

Support `charset` parameter for content type `application/x-www-form-encoded`

---

docs/locale/ja/LC_MESSAGES/operation.po

I translated ["Configuring and Running Zope"](https://zope.readthedocs.io/en/latest/operation.html) chapter (operation.html) into Japanese. It was from "Running Zope (plone.recipe.zope2instance install)" section to "Debugging Zope applications under WSGI" section.

Docs ja translation #1111

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

We cannot make a GET request that contains both a Content-Type header and a query string.
Examples that work fine:
```shell
$ curl https://classic.demo.plone.org/@@ok?bar=1
OK
$ curl -H 'Content-Type: text/plain' https://classic.demo.plone.org/@@ok
OK
```
Example that should work fine, but it is not working fine:
```shell
$ curl -H 'Content-Type: text/plain' https://classic.demo.plone.org/@@ok?a=1
{"error_type": "NotImplementedError"}
```
Example that should actually trigger the error:
```shell
$ curl -H 'Content-Type: text/plain' -d @<(echo b=1) https://classic.demo.plone.org/@@ok?a=1
{"error_type": "NotImplementedError"}
```
Fixes plone/plone.restapi#1611

Do not break with GET requests that have a query string and a Content-Type header 

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

Formerly, ZPublisher had the restriction to handle either request parameters (from a query string or a body with form data (i.e. a body with content type `application/x-www-form-urlencoded` or `multipart/form-data) or a request body not containing form data. A query string together with a body not containing form data raised a `NotImplementedError`.
This PR removes the restriction: request parameters from a query string can be combined with a request body not containing form data. Request parameters are made available in the request's `form` attribute (a `dict`), the request body can be accessed via the request key `BODY` (a `bytes` object) or `BODYFILE` (a file like object).
This PR fixes #1122.

Allow ZPublisher to handle a query string together with a request body

---

CHANGES.rst
src/App/Extensions.py
src/App/tests/fixtures/error.py
src/App/tests/fixtures/getObject.py
src/App/tests/test_Extensions.py

Since 4.0a6 the filename is missing there, resulting in problems while debugging (debugger is unable to show the code line) and coverage of Python modules loaded via Products.ExternalMethods.
The commit introducing this change was https://github.com/zopefoundation/Zope/commit/8d30ff802e60eae55711f200c3197916fa5f90e1
The previous code cannot be restored because in Python 3 `exec` no longer takes an open file as argument but just `str`, `bytes`, or `Code` objects.

Restore filename on code objects: `App.Extensions.getObject()`.

---

.github/workflows/tests.yml
CHANGES.rst
src/App/Extensions.py
src/App/tests/fixtures/error.py
src/App/tests/fixtures/getObject.py
src/App/tests/test_Extensions.py

Port of https://github.com/zopefoundation/Zope/pull/1138 to Zope 4.
I need this change for a customer on Zope 4 to fix coverage of code used by ExternalMethods.

Zope 4: Restore filename on code objects: `App.Extensions.getObject()`.

---

CHANGES.rst
src/ZPublisher/mapply.py
src/ZPublisher/tests/test_mapply.py

Fixes #1134.
This PR makes `mapply` `__signature__` aware.
`__signature__` has been introduced by Python 3 to allow (usually decorators) to specify the signature of a function. It makes it easy to implement signature preserving decorators.
With this PR `mapply` looks for `__signature__`  and (if present) uses it to determine the parameter names and their default. Otherwise, `mapply` determines this information as before.

Make `mapply`  `__signature__` aware

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/Zope2/Startup/handlers.py
src/Zope2/Startup/tests/test_schema.py
src/Zope2/Startup/wsgischema.xml
src/Zope2/utilities/skel/etc/zope.conf.in

make Zope's parameters for denial of service protection configurable

---

src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

This is a fix for yesterdays #1142 (therefore no separate change log entry).
The documentation for #1142 promised that `FORM_MEMORY_LIMIT` would limit the size of an access to `request.BODY`. Unfortunately, I forgot to make a test for this promise -- and indeed, the promise has been broken.
This PR adds the missing test and fixes the implementation.

fix (and test) limit for  `request.BODY`

---

CHANGES.rst
setup.py
src/App/dtml/manage.dtml
src/OFS/Application.py
src/OFS/tests/testApplication.py

The ZMI frame logic uses a request variable `came_from` to determine the source location for the right-hand side frame when JavaScript is disabled. This can be passed in via query string, which means it's out of our control and must be sanity-checked. Only site-local pages should load into that frame.

Tighten down the ZMI frame source logic to only allow site-local sources

---

CHANGES.rst
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_WSGIPublisher.py

This fixes a problem that user name was empty in access log for error pages.
Fixes #1155

WSGIPublisher: set REMOTE_USER even in case of error

---

CHANGES.rst
src/App/dtml/manage.dtml
src/OFS/Application.py
src/OFS/tests/testApplication.py

Backport to 4.x of PR #1151 and #1152.

Tighten down ZMI frame source logic to only allow site-local sources [4.x]

---

CHANGES.rst

I did this just now on the [backport to the 4.x branch](https://github.com/zopefoundation/Zope/pull/1160/files) as well.
Miguel reported the problem earlier this year to the security list.  We decided to fix it without security advisory, but crediting him would still be good.

Credit Miguel Segovia Gil for reporting a problem.

---

src/OFS/Image.py

In addition to https://github.com/zopefoundation/Zope/pull/1146:
SVG font files do not contain width/height dimension. This case of missing attrs is covered now and the preview show the browser rendered XML.

SVG-File: avoid attr error on missing dimensions

---

CHANGES.rst
src/OFS/Image.py
src/OFS/tests/testFileAndImage.py

ignore parameters and whitespace and normalize to lowercase.
Motivated by the report from Almir Zunic on "mailto:security@plone.org" " [p/z-sec] XSS - found in Management interface" I reexamined the logic developed for CVE-2023-42458 and found it incomplete. It compares the whole `content_type` against a list of types. But, at least if set manually, `content_type` can contain parameters and/or additional whitespace and may use uppercase letters which could not be directly compared with a types list.
When the logic is based on an allow list (the default), files with an unexpected `content_type` are delivered as attachment (which is safe). However, if the logic is based on a deny list, potentially dangerous files could be presented inline.
This PR bases the  CVE-2023-42458 logic on the …

Base logic for CVE-2023-42458 on the media type proper

---

src/App/dtml/manage_tabs.dtml
src/OFS/dtml/cmassoc.dtml
src/OFS/dtml/fileEdit.dtml
src/OFS/dtml/findForm.dtml

some dtml code cleaning of minor relevance

zmi: whitespace-cleanup, minor html fixes

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

Fixes #1171.
This PR honors a request's `Content-Length` if the incoming input stream is not seekable (and therefore, the WSGI server might not have done this already).
It should ensure correct behavior even if the WSGI server does not honor the WSGI recommendation to emulate an EOF once `Content-Length` bytes have been read. It works by wrapping the input stream implementing the recommendation.

honor a request's `Content-Length`

---

.meta.toml
src/ZPublisher/HTTPRequest.py
tox.ini

This PR applies https://github.com/zopefoundation/meta/pull/216 as well as https://github.com/zopefoundation/meta/commit/13b9049c6e3fbfbfa04bae5f18ff7396140e1933 to Zope and separates real linting steps, which should run every time, from package consistency checks, which are only important when making a release. That way the lint check will turn green again and contributors can merge their own PRs.

Separate lint and package checks

---

CHANGES.rst
src/App/ApplicationManager.py
src/App/DavLockManager.py
src/App/ZODBConnectionDebugger.py
src/App/dtml/dbMain.dtml
src/App/dtml/debug.dtml
src/App/dtml/zodbConnections.dtml
src/zmi/styles/resources/zmi_base.css

This PR creates a new Control Panel tab "ZODB Connections" that contains the ZODB connection information shown at the bottom of the former "Debug" page. Debug is renamed to "Reference Counts". The goal is to make this information easier to access and read.
When Zope is running and you visit the "Debug" page several times the page can get very long and getting to the ZODB connection information is inconvenient and cumbersome.
The new "ZODB Connections" page also aims to show more useful information at a glance. It hides the full request information at first and reveals it when you click on the request URI that is shown. The request data is also formatted and sorted now.

Separate ZODB connection information into new ZODB Connections view

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

Fixes #1182.
Unlike `multipart`, Zope did not support form data in `PUT` requests. This likely has been a bug: whether a request contains form data is not determined by the request method but by the content type.
This PR brings Zope in line with `multipart`: form data is processed for `POST` and `PUT` requests  controlled by the content type. Like `multipart`, form data is not processed for other request methods (even if the content type indicates form data) because `multipart` would reject those request methods.

support form data in PUT requests

---

CHANGES.rst
versions.cfg

Fixes #1188.
Steps after the PR is merged:

Officially support Python 3.12.1.

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

Since https://github.com/zopefoundation/Zope/pull/893 the Content-Disposition header supports non-ascii filenames, by containing the filename in ascii and the filename in UTF-8, but the ascii version was produced by applying `str` on a `bytes` instance, so it looks like `b'file.txt'` instead of `file.txt`.

Fix Content-Disposition header for clients without rfc6266 support

---

CHANGES.rst
src/App/dtml/manage_page_header.dtml
src/zmi/styles/tests.py

Fix authentication error viewing ZMI with a user defined outside of zope root

---

CHANGES.rst
src/App/ProductContext.py
src/App/tests/test_ProductContext.py

Work around for #1202.
`Products.CMFCore` and `Products.CMFPlone` register non callable constructors with `App.ProductContext.ProductContext.registerClass` (even though the method's docstring clearly states that constructors must be callable).
Formerly, this was not a problem. But with the introduction of explicit zpublishable decoration, constructors are now required to be callable braking `Products.CMFCore` and `Products.CMFPlone`.
The PR introduces the new parameter `resources` of `registerClass`  which should be used instead of `constructors` to register non callable objects. It uses work around code to avoid braking `Products.CMFCore` and `Products.CMFPlone` (and maybe other packages) when they abuse the `constructors` parameter for non callable objects; a `DeprecationWarning` is …

Work around `Products.CMFCore` and `Products.CMFPlone` design bug

---

CHANGES.rst
src/App/dtml/copyright.dtml
src/App/dtml/manage.dtml
src/App/dtml/manage_page_header.dtml
src/App/dtml/menu.dtml
src/zmi/styles/resources/logo/favicon/browserconfig.xml
src/zmi/styles/resources/logo/favicon/site.webmanifest
src/zmi/styles/subscriber.py
src/zmi/styles/tests.py

Fix authentication error viewing ZMI resource with virtual hosting

---

CHANGES.rst
src/zmi/styles/resources/logo/docs/README.md

For promoting Zope with it's logo graphics a Creative Commons license model would be very helpful. 
Today any usage of the logo may be legally unclear and will require an explicit confirmation by Zope/Plone Foundation.
E.g. Wikipedia is asking now for this explicit confirmation by the copyright owners, if the file may be published/referenced:
https://de.wikipedia.org/wiki/Datei:Zope.svg#file
Instead of sending an email to the wikimeda foundation by the concerned people I propose a standard licensing model as recommended here (german language):
https://de.wikipedia.org/wiki/Hilfe:FAQ_zu_Bildern
To make the usage easier, I have added some general information to the logo-readme file.  Looking forward to any comments.

Zope logo usage: CC-BY-4.0

---

CHANGES.rst
src/ZPublisher/BaseRequest.py
src/ZPublisher/tests/testBaseRequest.py

Return 404 instead of IndexError for traversal past the root

---

.github/workflows/tests.yml
.meta.toml
CHANGES.rst
constraints.txt
docs/INSTALL.rst
pyproject.toml
requirements-full.txt
setup.py
tox.ini
versions-prod.cfg
versions.cfg

Fixes #1176 
This PR declares Python 3.13 support and updates dependencies to Python 3.13-compatible versions.

Declare Python 3.13 compatibility

---

CHANGES.rst
src/ZPublisher/WSGIPublisher.py

set up `request["PARENTS"]` before request parameter processing

---

CHANGES.rst
src/OFS/dtml/cacheable.dtml

In https://github.com/zopefoundation/Zope/commit/6ac52aacbea61603b482332846cf356d78a744a6#diff-1cd7357f6a0c6126e3279998f27d3c17f5d48e4940356bbe6f0266101828fb02R9 the label was changed from `Cache this object using` to `New Cache this object using`, this looks like left-overs from debugging.

OFS/dtml/cacheable: Remove "New" from label

---

CHANGES.rst
src/OFS/Application.py

Fixes #1239.
Currently, Zope only supports file based module finders during product enumeration (see `OFS.Application.get_products`).
This PR replaces Zope's  proprietary product enumeration by `pkgutil.iter_modules` and thereby supports all module finder types supported by Python.
To reduce the risk for incompatibilities the signature for product handling functions in `OFS.Application` is mostly left unchanged: `product_dir` is replaced by `finder` (though most functions do not use this parameter in their body).

Use modern Python import features for product enumeration

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

HTTPRequest: close file uploads to prevent ResourceWarning

---

CHANGES.rst
src/OFS/Image.py
src/OFS/dtml/fileEdit.dtml
src/OFS/tests/testFileAndImage.py

Modernize a bit the condition to display online text editor: support editing json inline and tolerate larger file content.

Enable ZMI History tab for ``OFS.Image.File``

---

CHANGES.rst
src/ZPublisher/BaseRequest.py

This can happen in Plone with spam/pentests hitting @@images without a further traversal.
```
ViewNotCallableError: __call__
File "ZPublisher/WSGIPublisher.py", line 181, in transaction_pubevents
yield
File "ZPublisher/WSGIPublisher.py", line 391, in publish_module
response = _publish(request, new_mod_info)
File "ZPublisher/WSGIPublisher.py", line 269, in publish
obj = request.traverse(path, validated_hook=validate_user)
File "ZPublisher/BaseRequest.py", line 483, in traverse
object, default_path = adapter.browserDefault(self)
File "/app/eggs/zope.browserpage-4.4.0-py3.9.egg/zope/browserpage/metaconfigure.py", line 434, in browserDefault
meth = getattr(self, attr)
File "app/eggs/Zope-5.8.5-py3.9.egg/Products/Five/browser/metaconfigure.py", line 448, in __call__
raise …
```

handle ViewNotCallableError as 404

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

This covers additional cases I have been seeing in the wild over the last couple months. I also added a unit test for https://github.com/zopefoundation/Zope/pull/1244.

Deny more potentially malicious requests with BadRequest

---

CHANGES.rst
setup.py
src/App/config.py
src/ZPublisher/HTTPRequest.py
src/Zope2/Startup/tests/test_schema.py
src/Zope2/Startup/wsgischema.xml
src/Zope2/utilities/skel/etc/zope.conf.in

Zope always had support for XML-RPC and other than registering a utility to decide whether to allow it there was no simple way to just turn it off. This PR adds a zope.conf switch to do just that.
The new configuration option is still "on" by default so no one will be surprised. You have to explicitly set it to "off" to disable XML-RPC requests. At that point those are answered by a BadRequest.
I want to add this switch because very few people actually use XML-RPC and I am seeing an increase in malicious and/or spam requests that are detected as XML-RPC in Zope's simple logic (POST with content type `text/xml`) and then cause uncontrolled exceptions in the XML parsing. IMHO everyone should turn this off unless it is really needed.

Add configuration switch to turn off the built-in XML-RPC support
