doc/CHANGES.rst
src/ZPublisher/WSGIPublisher.py

See https://bugs.launchpad.net/zope2/+bug/1465432
Backport 41594f6d83a1c2599751b6faf8abd26c99a1d0d1 and c73dfcd1d8216dc06db1fc3692269a86ed37631d from master.

WSGI begin / end interaction fixes

---

src/Zope2/Startup/__init__.py

Pull-Request for master branch.
Discussion see https://github.com/zopefoundation/Zope/commit/87c5992e7e40604df206bb713e42bafd5919fe64

Don't bail on WindowsError which is not existing on non-windows systems.

---

src/App/ApplicationManager.py

Harden module-crawling against trickery performed by six.
Commit details: 3710b7fef474eb866495c0fe80cb37e5ea5a7b1f

Cherry-picked commit 3710b7f from master to 2.13 branch.

---

doc/CHANGES.rst
src/Zope2/Startup/zopeschema.xml

@tseaver I am adding a pull request for https://github.com/zopefoundation/Zope/issues/43
Issue is described in detail within the issue.

Pull request for issue #43

---

CHANGES.rst
src/OFS/ObjectManager.py

Optimized the `OFS.ObjectManager.__contains__` method to do the least amount of work necessary.

Optimize "OFS.ObjectManager.__contains__" method

---

doc/CHANGES.rst
src/OFS/ObjectManager.py

Optimize "OFS.ObjectManager.__contains__" method (backport)

---

doc/CHANGES.rst
src/OFS/Application.py
src/OFS/Cache.py
src/OFS/DTMLMethod.py
src/OFS/Image.py
src/OFS/ObjectManager.py
src/OFS/OrderSupport.py
src/OFS/PropertySheets.py
src/OFS/SimpleItem.py
src/OFS/Traversable.py
src/OFS/ZDOM.py

This is a rebased version of #54.

Apply hotfix 20160419 rebased

---

versions-prod.cfg

It will be needed by AccessControl 4.0

Pin AuthEncoding

---

CHANGES.rst
src/App/dtml/manage_tabs.dtml

Quote variable in manage_tabs to avoid XSS [master]

---

doc/CHANGES.rst
src/App/dtml/manage_tabs.dtml
src/Products/Transience/dtml/manageTransientObjectContainer.dtml

Quote variables in manage_tabs and manage_container to avoid XSS [2.13]

---

CHANGES.rst
src/OFS/CopySupport.py
src/OFS/tests/testCopySupport.py

From Products.PloneHotfix20161129.
Same as #83 but now for master.

Don't copy items the user is not allowed to view. [master]

---

doc/CHANGES.rst
src/OFS/CopySupport.py
src/OFS/tests/testCopySupport.py

From Products.PloneHotfix20161129.

Don't copy items the user is not allowed to view. [2.13]

---

doc/CHANGES.rst
src/OFS/dtml/findResult.dtml

This is one part of the [hotfix](https://plone.org/security/hotfix/20170117). The other part may also need fixing in Zope. I'll have a look at that later.

Apply plonehotfix 20170717 [2.13]

---

CHANGES.rst
src/OFS/dtml/findResult.dtml

This is one part of the hotfix. The other part may also need fixing in Zope. I'll have a look at that later.

Apply plonehotfix 20170717 [master]

---

src/Testing/ZopeTestCase/zopedoctest/functional.py

Same as #89 but now for master.

Fixed dummy runTest on functional test case. [master]

---

src/ZPublisher/WSGIPublisher.py

* Avoid converting exception type if it's a subclass of the preferred HTTP exception
* Preserve the original traceback on Python 2

A couple fixes for WSGI publisher exception handling

---

buildout.cfg
src/OFS/DTMLDocument.py
src/OFS/DTMLMethod.py
src/OFS/Image.py
src/OFS/role.py
src/OFS/tests/testFileAndImage.py
src/OFS/tests/testObjectManager.py
src/OFS/tests/testRanges.py
src/OFS/tests/test_DTMLDocument.py
src/OFS/tests/test_DTMLMethod.py
src/OFS/tests/test_subscribers.py
src/OFS/tests/test_userfolder.py
src/Shared/DC/Scripts/Bindings.py
src/Testing/ZopeTestCase/functional.py
src/Testing/ZopeTestCase/testFunctional.py
src/Testing/ZopeTestCase/testZODBCompat.py
src/Testing/ZopeTestCase/zopedoctest/functional.py
src/Testing/ZopeTestCase/zopedoctest/testFunctionalDocTest.py
src/Testing/makerequest.py
src/Testing/tests/test_makerequest.py
src/Testing/tests/test_testbrowser.py
src/ZPublisher/BaseResponse.py
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPRequest.py
src/ZPublisher/tests/testHTTPResponse.py

Another large round of fixes, related to treating the body as bytes.

More Python 3 fixes.

---

.travis.yml
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

Here is the fix as discussed in #148 .

Fix usage of FieldStorage.

---

CHANGES.rst
buildout.cfg
requirements-full.txt
util.py
versions-prod.cfg

This removes the last non-ported dependency mentioned in #39.

Made Products.MailHost an optional dependency.

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

Fix special double under methods on `HTTPRequest.record` class

---

requirements-full.txt
versions-prod.cfg

Update to Zope2 4.0b1 release.

---

src/ZPublisher/HTTPRequest.py

Fix rendering of cookies when using 'str(request)'

---

CHANGES.rst
buildout.cfg
src/OFS/Application.py
src/OFS/tests/testApplication.py

Make Redirect unavailable as url [master]

---

doc/CHANGES.rst
src/OFS/Application.py
src/OFS/tests/testApplication.py

Make Redirect unavailable as url [2.13]

---

src/ZPublisher/HTTPRequest.py

The stdlib bug which caused us to fork it is long gone, and we have our own Py3k bug now.
Leave behind a BBB alias, in case anybody is expecting to import it.
Closes #223.
Closes #204.

Drop 'ZopeFieldStorage' in favor of 'cgi.FieldStorage'.

---

src/ZPublisher/HTTPRequest.py

See https://github.com/zopefoundation/Zope/commit/e2f83e6c26204477fc860cbf66e5b766e5e663f7#commitcomment-26134188

Import FieldStorage directly to reenable a patch in plone.app.blob

---

docs/INSTALL-buildout.rst
docs/INSTALL-virtualenv.rst
docs/conf.py

Doc how to use ZServer nowadays

---

CHANGES.rst
src/OFS/CopySupport.py
src/OFS/tests/testCopySupport.py

6ca3691 introduces code to prevent a DoS attack.
This is PR mitigates the consequences for file system code by allowing to paste without limits as discussed in #217.
This PR is for `master` if it is accepted I'm going to create one for `2.13`, too.

Add ability to paste objects without limits.

---

src/OFS/Application.py

Zope/src/OFS/Application.py:213: DeprecationWarning: Expected text
transaction.get().note(note)

Fix DeprecationWarning in commit message text

---

docs/zope2book/SearchingZCatalog.rst

fix spelling error

---

CHANGES.rst
src/zmi/styles/resources/zmi_base.js

Fix action extraction for addItem.

---

docs/operation.rst
src/Zope2/Startup/starter.py
src/Zope2/Startup/wsgischema.xml
src/Zope2/utilities/skel/etc/wsgi.conf.in

Also, some documentation of possible config settings.

Use system locale if no locale is set in config

---

CHANGES.rst
src/OFS/ObjectManager.py
src/OFS/tests/testSorting.py
src/OFS/zpt/main.zpt
src/zmi/styles/resources/zmi_base.css

Restore support for ordered folders in ZMI

---

appveyor.yml

fix appveyor

---

CHANGES.rst
docs/operation.rst
setup.py
src/Zope2/utilities/tests/test_zconsole.py
src/Zope2/utilities/zconsole.py

See https://github.com/zopefoundation/Zope/issues/310, https://github.com/plone/plone.recipe.zope2instance/issues/49

Run scripts/debug console

---

src/App/tests/testImageFile.py
src/ZPublisher/tests/test_xmlrpc.py

s. https://github.com/zopefoundation/Zope/issues/268

Fix deprecation and resource warnings

---

CHANGES.rst

We did not add a changelog entry on #314
Also, it's not clear to me if this qualifies as Bug fix or new feature.

Add changelog entry for #314

---

doc/CHANGES.rst

That changelog entry was referencing another PR

Zope 2.13: fixup! Add change log entry for #395

---

src/OFS/dtml/access.dtml
src/zmi/styles/resources/zmi_base.css

Here's a start at fixing issues raised by Andreas in #451. I'm not a CSS expert, btw.

manage_access cosmetics

---

CHANGES.rst
docs/WHATSNEW.rst
src/App/dtml/manage_page_header.dtml
src/OFS/Image.py
src/OFS/dtml/fileEdit.dtml
src/OFS/dtml/properties.dtml
src/OFS/tests/testFileAndImage.py
src/Products/PageTemplates/tests/testExpressions.py
src/Products/PageTemplates/tests/testZopePageTemplate.py
src/Products/PageTemplates/unicodeconflictresolver.py
src/Products/PageTemplates/www/ptEdit.zpt

Removed support for management_page_charset

---

CHANGES.rst
src/App/dtml/manage.dtml
src/App/dtml/manage_navbar.dtml
src/App/dtml/manage_page_footer.dtml
src/App/dtml/manage_page_header.dtml
src/App/dtml/menu.dtml
src/zmi/styles/resources/zmi.localstorage.api.js
src/zmi/styles/resources/zmi_base.js

Fix confusing and broken button to show/hide the left-hand tree pane

---

docs/zdgbook/ObjectPublishing.rst

... for the upcoming Zope 4 release.
No skipped CI as otherwise only admins could merge.
The plan is to have several small PRs instead of a huge one, which nobody wants to review.
cf #252

Update introduction of ObjectPublishing

---

CHANGES.rst
src/OFS/Image.py
src/OFS/tests/testFileAndImage.py

Fix error when not selecting a file for upload in Files and Images

---

CHANGES.rst
src/App/dtml/manage_navbar.dtml
src/zmi/styles/resources/zmi_base.js

Fixes #505 
Fixes #506 
Replacement for PR #507 -- now inside `zopefoundation/Zope` as requested by @dataflake

Zmi add fix #505 (single add item) and #506 ("addItemSelect" handling) 

---

docs/zdgbook/ObjectPublishing.rst

No skipped ci as otherwise only admins can merge.

Improve wording.

---

docs/zdgbook/ObjectPublishing.rst

Also:
- fix minor grammar error
- improve docstrings in example code
- prefer "subobject" over "sub-object"

Improve formatting

---

CHANGES.rst
src/zmi/styles/resources/zmi_base.css

fix ZMI font rendering on macOS

---

docs/zdgbook/ObjectPublishing.rst

- fix minor wording and comma issues
- improve example code
- add note about empty return values / 204 status code

Revise section "HTTP Responses"

---

docs/zdgbook/ObjectPublishing.rst

- fix reference to "Security" chapter
- fix typo

Revise section "Traversal and Security".

---

docs/zdgbook/ObjectPublishing.rst

- fix typos
- improve doc string

Revise sub-sections about argument marshalling.

---

docs/zdgbook/ObjectPublishing.rst

cf https://github.com/zopefoundation/Zope/pull/552#issuecomment-483443498

Remove previously, wrongly added variables.

---

CHANGES.rst
setup.py
src/OFS/__init__.py

Fixes https://github.com/plone/Products.CMFPlone/issues/2800

add zodbupdate info to move webdav.LockItem to OFS.LockItem

---

docs/zdgbook/ObjectPublishing.rst
src/ZPublisher/Converters.py
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/test_Converters.py

- improve code example
- add missing converters
- improve existing description of converters
- add note about client-side validation

Revise section "argument conversion"

---

src/ZPublisher/HTTPRequest.py

modified:   src/ZPublisher/HTTPRequest.py

Remove unused variable.

---

docs/zdgbook/ObjectPublishing.rst

Revise section "Record Arguments"
- fix typos
- lowercase all html tags

Revise section "Record arguments"

---

src/ZTUtils/Zope.py

modified:   src/ZTUtils/Zope.py

Fix typos.

---

docs/zdgbook/ObjectPublishing.rst

Just after the merge of pr #596  some more improvement suggestions by icemac
popped.
-> integrate suggestions

Improve wording for section "Exceptions".

---

docs/zdgbook/ObjectPublishing.rst

- remove wrong information
- udpate example

Revise section "Manual Access to Request and Response".

---

docs/zdgbook/ObjectPublishing.rst
docs/zdgbook/Products.rst

- remove "work in progress" for Chapter 4
- add "work in progress" for Chapter 5
- revise "Introduction"
modified:   docs/zdgbook/Products.rst

Start revising Chapter 5 "Zope Products".

---

src/OFS/ObjectManager.py
src/OFS/PropertySheets.py
src/OFS/bbb.py
src/OFS/tests/testObjectManager.py
src/OFS/tests/testProperties.py

Fixes bug introduced in https://github.com/zopefoundation/Zope/commit/b4495eb403c622300b02071a0904b3ad948cc4fe?diff=unified&w=1#diff-3bb20756c73e7cac2fb14728c89e578aR472

Fix bug when getting propertysheet and bugs in manage_FTPlist

---

docs/zdgbook/examples/Poll.py
docs/zdgbook/examples/PollImplementation.py
docs/zdgbook/examples/PollProduct.py
tox.ini

I did not port the code in the examples to a current version of `zope.interface` as this PR is only about linting.

Simplify linting configuration and lint docs, too.

---

CHANGES.rst
constraints.txt
requirements-full.txt
versions-prod.cfg

Pin Paste, too as it is used in zope.ini.

---

CHANGES.rst
src/App/dtml/copyright.dtml
src/App/dtml/manage.dtml
src/App/dtml/manage_page_header.dtml
src/App/dtml/menu.dtml

Fix broken ZMI when using non-root deployments.

---

src/OFS/DTMLMethod.py
src/OFS/FindSupport.py
src/OFS/tests/testFileAndImage.py
src/OFS/tests/testSimpleItem.py
src/Products/PageTemplates/tests/test_pagetemplate.py
src/Products/PageTemplates/tests/util.py
src/ZPublisher/HTTPRequest.py
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/test_Converters.py
src/ZPublisher/utils.py

Grep for `PY3` and drop Python 2 support.

---

src/App/ProductContext.py
src/App/ZApplication.py
src/OFS/OrderSupport.py
src/Products/Five/fiveconfigure.py
src/Testing/ZopeTestCase/zopedoctest/functional.py
src/ZPublisher/HTTPResponse.py
src/ZPublisher/WSGIPublisher.py
src/ZPublisher/tests/testHTTPRequest.py

Remove Python 2 support code guarded by sys.version*.

---

src/OFS/Traversable.py

[4.x] Update comment

---

docs/zdgbook/ComponentsAndInterfaces.rst

modified:   docs/zdgbook/ComponentsAndInterfaces.rst

Fix minor glitches in Components and Interfaces documentation.

---

CHANGES.rst
src/webdav/PropertySheets.py

Fixes Zope-797 (improper encoding of the WebDAV displayname property)

---

src/ZPublisher/tests/testHTTPResponse.py
src/Zope2/utilities/zconsole.py

Fix Flake8 issues after new flake8 release.

---

docs/zopebook/Sessions.rst

This is a first go at documenting my findings as to how server-side sessions in zope can be salvaged / made to work again.
I'd appreciate feedback!

Document my findings on server side sessions in Zope 4+.

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

Improve solidity of the ``debugError`` method

---

src/App/dtml/davLockManager.dtml
src/zmi/styles/resources/zmi_base.css
src/zmi/styles/resources/zmi_base.js

Hello @dataflake ,
i fixed some minor zmi issues:
1. element nesting of davlock-gui
2. placing the helptext-block in modal-popup into the main-block 
Best regards
f

ZMI: davlock, modal-win

---

.pre-commit-config.yaml
.travis.yml
CHANGES.rst
src/Products/PageTemplates/Expressions.py
src/Products/PageTemplates/engine.py
src/Products/PageTemplates/tests/testC2ZContext.py
src/Products/PageTemplates/tests/testVariables.py
src/Products/PageTemplates/tests/testZopeAwareEngine.py
tox.ini
util.py

`pre-commit` is a linter runner, which does all the heavy lifting of finding the correct files to lint, recursively.
Also, `pre-commit` both able to pin package versions, and to autoupdate all at once if desired.

Add pyupgrade via pre-commit

---

docs/migrations/zope4/removed.rst

Update seasoning documentation hint and link the chapter on sessions.
Not sure this is the best way to link to the zope book - guidance on the right way to link this would be very welcome.

Better session documentation and link

---

CHANGES.rst
src/Products/PageTemplates/engine.py
src/Products/PageTemplates/tests/input/RepeatVariable.html
src/Products/PageTemplates/tests/output/RepeatVariable.html

Pass sequence to "RepeatItem" (rather than an interator)

---

CHANGES.rst
src/Products/PageTemplates/engine.py
src/Products/PageTemplates/tests/input/RepeatVariable.html
src/Products/PageTemplates/tests/output/RepeatVariable.html

Forward port of #914 to "master"

---

CHANGES.rst
src/zmi/styles/resources/zmi_base.css

Hi @icemac / @jugmac00,
here come style fix according to https://github.com/zopefoundation/Products.SiteErrorLog/issues/26
Best regards
f
fixes zopefoundation/Products.SiteErrorLog#26

zmi: fixed Products.SiteErrorLog/issues/26

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

This is the port of #930 to `master`.

convert `bytes` `HTTPResponse` header value to `str`

---

src/zmi/styles/resources/zmi_base.css

Hi @dataflake ,
according to my pull-request "ZMI upgraded to Zope4+" for Products.SQLAlchemyDA 
https://github.com/zopefoundation/Products.SQLAlchemyDA/compare/ZMI--Upgrade-to-Zope4+
I added minor CSS changes.
Best regards

ZMI  sqlalchemyda

---

docs/conf.py
requirements-rtd.txt
setup.py

... which even broke the build process for documentation.
This fixes #967.

remove unused Sphinx dependency

---

CHANGES.rst
src/App/version_txt.py

Fixes #999, the potential race condition reported by @fazalsulaiman.

Fix potential race condition in `App.version_txt`

---

CHANGES.rst
src/App/version_txt.py

In #1000, I have introduced a wrong reference in `CHANGES.rst` (copy & paste error), fixed with this PR.

Changes.rst fix reference#1000

---

.meta.toml
tox.ini

Currently the GHA job running the linter is broken.

Fix lint environment.

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/tests/testHTTPResponse.py

quote all components of redirect URL (not only path) (#1032)

---

CHANGES.rst
src/Products/PageTemplates/Extensions/find_bad_templates.py

add FS PageTemplates, show html tags

improvements on find_bad_templates  (#1042)

---

src/Shared/DC/Scripts/Signature.py

See https://github.com/Zopefoundation/Zope/commit/740eb601fb9660246e84fe6a58c37a18202e3ef2#diff-b5be5ab2f8e6054e0ae6307d7d23d8d406d47f8a9c18e52fbb7461ce04305acaR46

Remove useless double assignment

---

CHANGES.rst
src/ZPublisher/HTTPResponse.py
src/ZPublisher/cookie.py
src/ZPublisher/tests/test_cookie.py

This forward ports #1053 to `master`.

forward port #1053 to `master`

---

CHANGES.rst
src/Testing/ZopeTestCase/functional.py
src/Testing/ZopeTestCase/testFunctional.py
src/Testing/ZopeTestCase/zopedoctest/functional.py

see https://github.com/zopefoundation/Zope/issues/1058

testing: backport #1059 on 4.x

---

CHANGES.rst
src/ZPublisher/Converters.py
src/ZPublisher/tests/test_Converters.py

Added `:json` converter in `ZPublisher.Converters`.

---

.meta.toml
CHANGES.rst
setup.py

Maybe additionally we need some of the new releases of dependencies created for 3.11.

Support Python 3.11.

---

CHANGES.rst
src/App/special_dtml.py
src/App/tests/testManagement.py

Fixes #1078 
There may be more affected pages

Fix broken ZMI pages due to the changed default content type

---

CHANGES.rst
src/ZPublisher/HTTPRequest.py
src/ZPublisher/tests/testHTTPRequest.py

Sanitize tainting (forward port of PR 1097)

---

sources.cfg

I created most of these branches myself today, with as starting point the master branches before the recent updates to drop Python 2.7.

Update sources.cfg to use maintenance branches.

---

CHANGES.rst
src/OFS/tests/testAppInitializer.py
src/Products/PageTemplates/tests/test_ptfile.py
src/Zope2/Startup/tests/test_schema.py
src/Zope2/Startup/tests/test_starter.py
src/Zope2/utilities/mkwsgiinstance.py

First cut with just Python suggestions

Implement code change suggestions from CodeQL scanning

---

src/OFS/Application.py

Rather than a booking `i = i + 1`

Use builtin enumerate

---

src/OFS/Application.py
src/OFS/tests/testApplication.py

Do not accept a 'tainted' came_from parameter.
Do not accept a came_from path-only url starting with `//` either. Browsers can interpret the rest of the path as a domain.
A question here is: can we rely on possibly dangerous came_from parameters to always automatically be marked as tainted?
I tried adding this test:
```
request['came_from'] = '<script>alert("hi");</script>'
self.assertEqual(app.getZMIMainFrameTarget(request),
f'{URL1}/manage_workspace')
```
This fails, both on master and with the current PR:
```
Failure in test test_getZMIMainFrameTarget (OFS.tests.testApplication.ApplicationTests.test_getZMIMainFrameTarget)
File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in …
```

Harden getZMIMainFrameTarget

---

.github/workflows/tests.yml
.meta.toml
constraints.txt
requirements-full.txt
tox.ini
versions-prod.cfg

Not yet testing on Python 3.13 as installing fails while building cffi.

Update to a RestrictedPython version which can be installed on Python 3.13.

---

CHANGES.rst
src/Products/PageTemplates/Expressions.py
src/Products/PageTemplates/expression.py
src/Products/PageTemplates/tests/structure.pt
src/Products/PageTemplates/tests/test_pagetemplate.py

Support the `Chameleon` expression type `structure`

---

.github/workflows/tests.yml
.meta.toml
MANIFEST.in
setup.cfg
tox.ini

The GHA action `ubuntu-release-check` was broken: https://github.com/zopefoundation/Zope/actions/runs/10339558885/job/28619071525
Also using https://github.com/zopefoundation/meta/pull/264 to require MacOS to be successful.

Fix MANIFEST.in
